#!/usr/bin/env python3
"""Generate design-system components."""

from __future__ import annotations

import argparse
import difflib
import os
from pathlib import Path


GENERATED_HEADER = "Generated by design-architect. Do not edit manually."


SWIFT = f"""// {GENERATED_HEADER}
// swiftlint:disable all

import SwiftUI

public enum OMSButtonVariant: Sendable {{
    case primary
    case secondary
    case dangerPrimary
    case dangerSecondary
}}

public enum OMSButtonSize: Sendable {{
    case small
    case medium
    case large
}}

public enum OMSLabelVariant: Sendable {{
    case title
    case body
    case caption
    case subtle
    case error
}}

public enum OMSFieldState: Sendable {{
    case normal
    case error(String)
    case disabled
}}

public enum OMSBadgeVariant: Sendable {{
    case info
    case neutral
    case success
    case warning
    case danger
}}

public enum OMSAlertVariant: Sendable {{
    case info
    case success
    case warning
    case danger
}}

public enum OMSTokens {{
    public enum Color {{
        public static let slate50 = SwiftUI.Color(red: 0.96, green: 0.96, blue: 0.99)
        public static let slate100 = SwiftUI.Color(red: 0.93, green: 0.94, blue: 0.98)
        public static let slate200 = SwiftUI.Color(red: 0.87, green: 0.89, blue: 0.94)
        public static let slate300 = SwiftUI.Color(red: 0.78, green: 0.81, blue: 0.88)
        public static let slate400 = SwiftUI.Color(red: 0.57, green: 0.62, blue: 0.73)
        public static let slate500 = SwiftUI.Color(red: 0.39, green: 0.44, blue: 0.56)
        public static let slate800 = SwiftUI.Color(red: 0.13, green: 0.15, blue: 0.27)
        public static let slate900 = SwiftUI.Color(red: 0.08, green: 0.09, blue: 0.21)
        public static let slate950 = SwiftUI.Color(red: 0.04, green: 0.02, blue: 0.14)
        public static let purple50 = SwiftUI.Color(red: 0.96, green: 0.95, blue: 0.98)
        public static let purple100 = SwiftUI.Color(red: 0.92, green: 0.89, blue: 0.96)
        public static let purple200 = SwiftUI.Color(red: 0.84, green: 0.77, blue: 0.95)
        public static let purple300 = SwiftUI.Color(red: 0.72, green: 0.56, blue: 0.94)
        public static let purple500 = SwiftUI.Color(red: 0.40, green: 0.05, blue: 0.90)
        public static let purple700 = SwiftUI.Color(red: 0.25, green: 0.04, blue: 0.56)
        public static let red50 = SwiftUI.Color(red: 1.00, green: 0.95, blue: 0.95)
        public static let red100 = SwiftUI.Color(red: 1.00, green: 0.89, blue: 0.89)
        public static let red200 = SwiftUI.Color(red: 1.00, green: 0.79, blue: 0.79)
        public static let red400 = SwiftUI.Color(red: 0.97, green: 0.44, blue: 0.44)
        public static let red500 = SwiftUI.Color(red: 0.94, green: 0.27, blue: 0.27)
        public static let red600 = SwiftUI.Color(red: 0.86, green: 0.15, blue: 0.15)
        public static let red700 = SwiftUI.Color(red: 0.73, green: 0.11, blue: 0.11)
        public static let red800 = SwiftUI.Color(red: 0.60, green: 0.11, blue: 0.11)
        public static let emerald50 = SwiftUI.Color(red: 0.93, green: 0.99, blue: 0.96)
        public static let emerald200 = SwiftUI.Color(red: 0.65, green: 0.95, blue: 0.82)
        public static let emerald700 = SwiftUI.Color(red: 0.02, green: 0.47, blue: 0.34)
        public static let orange50 = SwiftUI.Color(red: 1.00, green: 0.97, blue: 0.93)
        public static let orange200 = SwiftUI.Color(red: 1.00, green: 0.84, blue: 0.67)
        public static let amber700 = SwiftUI.Color(red: 0.71, green: 0.33, blue: 0.04)
        public static let surface = SwiftUI.Color.white
        public static let page = slate50
        public static let ink = slate900
        public static let mutedInk = slate500
        public static let border = slate300
        public static let brand = purple500
        public static let success = emerald700
        public static let warning = amber700
        public static let danger = red700
    }}

    public enum Radius {{
        public static let button: CGFloat = 8
        public static let buttonLarge: CGFloat = 12
        public static let input: CGFloat = 12
        public static let badge: CGFloat = 16
        public static let card: CGFloat = 24
    }}

    public enum Spacing {{
        public static let xsmall: CGFloat = 4
        public static let small: CGFloat = 8
        public static let medium: CGFloat = 12
        public static let large: CGFloat = 16
        public static let xlarge: CGFloat = 24
    }}
}}

public struct OMSButtonStyle: ButtonStyle {{
    private let variant: OMSButtonVariant
    private let size: OMSButtonSize
    private let fillsWidth: Bool

    public init(
        variant: OMSButtonVariant = .primary,
        size: OMSButtonSize = .medium,
        fillsWidth: Bool = false
    ) {{
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
    }}

    public func makeBody(configuration: Configuration) -> some View {{
        configuration.label
            .font(font)
            .lineLimit(1)
            .minimumScaleFactor(0.9)
            .padding(.horizontal, horizontalPadding)
            .frame(minHeight: height)
            .frame(maxWidth: fillsWidth ? .infinity : nil)
            .background(backgroundColor(isPressed: configuration.isPressed))
            .foregroundStyle(foregroundColor)
            .overlay(
                RoundedRectangle(cornerRadius: cornerRadius)
                    .stroke(borderColor, lineWidth: borderColor == .clear ? 0 : 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: cornerRadius))
            .contentShape(RoundedRectangle(cornerRadius: cornerRadius))
    }}

    private var font: Font {{
        switch size {{
        case .small:
            return .custom("Fustat", size: 12).weight(.bold)
        case .medium:
            return .custom("Fustat", size: 14).weight(.bold)
        case .large:
            return .custom("Fustat", size: 16).weight(.bold)
        }}
    }}

    private var height: CGFloat {{
        switch size {{
        case .small:
            return 30
        case .medium:
            return 32
        case .large:
            return 40
        }}
    }}

    private var horizontalPadding: CGFloat {{
        switch size {{
        case .small:
            return 8
        case .medium:
            return 12
        case .large:
            return 12
        }}
    }}

    private var cornerRadius: CGFloat {{
        switch size {{
        case .large:
            return OMSTokens.Radius.buttonLarge
        case .medium, .small:
            return OMSTokens.Radius.button
        }}
    }}

    private func backgroundColor(isPressed: Bool) -> SwiftUI.Color {{
        switch variant {{
        case .primary:
            return isPressed ? OMSTokens.Color.purple700 : OMSTokens.Color.slate950
        case .secondary:
            return isPressed ? OMSTokens.Color.purple100 : OMSTokens.Color.surface
        case .dangerPrimary:
            return isPressed ? OMSTokens.Color.red800 : OMSTokens.Color.red600
        case .dangerSecondary:
            return isPressed ? OMSTokens.Color.red100 : OMSTokens.Color.surface
        }}
    }}

    private var foregroundColor: SwiftUI.Color {{
        switch variant {{
        case .primary, .dangerPrimary:
            return .white
        case .secondary, .dangerSecondary:
            return OMSTokens.Color.slate950
        }}
    }}

    private var borderColor: SwiftUI.Color {{
        switch variant {{
        case .primary, .dangerPrimary:
            return .clear
        case .secondary:
            return OMSTokens.Color.slate500
        case .dangerSecondary:
            return OMSTokens.Color.red600
        }}
    }}
}}

public struct OMSButton: View {{
    private let variant: OMSButtonVariant
    private let size: OMSButtonSize
    private let fillsWidth: Bool
    private let text: String
    private let action: () -> Void

    public init(
        _ text: String,
        variant: OMSButtonVariant = .primary,
        size: OMSButtonSize = .medium,
        fillsWidth: Bool = false,
        action: @escaping () -> Void
    ) {{
        self.text = text
        self.variant = variant
        self.size = size
        self.fillsWidth = fillsWidth
        self.action = action
    }}

    public var body: some View {{
        Button(text, action: action)
            .buttonStyle(OMSButtonStyle(variant: variant, size: size, fillsWidth: fillsWidth))
    }}
}}

public struct OMSIconButton: View {{
    private let systemImage: String
    private let accessibilityLabel: String
    private let size: CGFloat
    private let action: () -> Void

    public init(
        systemImage: String,
        accessibilityLabel: String,
        size: CGFloat = 40,
        action: @escaping () -> Void
    ) {{
        self.systemImage = systemImage
        self.accessibilityLabel = accessibilityLabel
        self.size = size
        self.action = action
    }}

    public var body: some View {{
        Button(action: action) {{
            Image(systemName: systemImage)
                .font(.system(size: size * 0.38, weight: .semibold))
                .frame(width: size, height: size)
                .background(OMSTokens.Color.surface)
                .foregroundStyle(OMSTokens.Color.slate950)
                .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.buttonLarge).stroke(OMSTokens.Color.slate300, lineWidth: 1))
                .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.buttonLarge))
        }}
        .buttonStyle(.plain)
        .accessibilityLabel(accessibilityLabel)
    }}
}}

public struct OMSIconLabelButton: View {{
    private let systemImage: String
    private let text: String
    private let action: () -> Void

    public init(systemImage: String, text: String, action: @escaping () -> Void) {{
        self.systemImage = systemImage
        self.text = text
        self.action = action
    }}

    public var body: some View {{
        VStack(spacing: OMSTokens.Spacing.small) {{
            OMSIconButton(systemImage: systemImage, accessibilityLabel: text, size: 40, action: action)
            Text(text)
                .font(.custom("Fustat", size: 12).weight(.medium))
                .foregroundStyle(OMSTokens.Color.slate900)
                .multilineTextAlignment(.center)
        }}
    }}
}}

public struct OMSLabel: View {{
    private let text: String
    private let variant: OMSLabelVariant

    public init(_ text: String, variant: OMSLabelVariant = .body) {{
        self.text = text
        self.variant = variant
    }}

    public var body: some View {{
        Text(text)
            .font(font)
            .foregroundStyle(color)
            .fixedSize(horizontal: false, vertical: true)
    }}

    private var font: Font {{
        switch variant {{
        case .title:
            return .custom("Fustat", size: 24).weight(.bold)
        case .body:
            return .custom("Fustat", size: 16).weight(.medium)
        case .caption:
            return .custom("Fustat", size: 14).weight(.medium)
        case .subtle:
            return .custom("Fustat", size: 12).weight(.medium)
        case .error:
            return .custom("Fustat", size: 14).weight(.medium)
        }}
    }}

    private var color: SwiftUI.Color {{
        switch variant {{
        case .title:
            return OMSTokens.Color.slate950
        case .body:
            return OMSTokens.Color.slate900
        case .caption, .subtle:
            return OMSTokens.Color.slate500
        case .error:
            return OMSTokens.Color.red700
        }}
    }}
}}

public struct OMSInputField: View {{
    private let title: String
    private let placeholder: String
    private let helperText: String?
    private let state: OMSFieldState
    @Binding private var text: String

    public init(
        _ title: String,
        text: Binding<String>,
        placeholder: String = "",
        helperText: String? = nil,
        state: OMSFieldState = .normal
    ) {{
        self.title = title
        self._text = text
        self.placeholder = placeholder
        self.helperText = helperText
        self.state = state
    }}

    public var body: some View {{
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.xsmall) {{
            OMSLabel(title, variant: .caption)
            TextField(placeholder, text: $text)
                .disabled(isDisabled)
                .padding(.horizontal, OMSTokens.Spacing.medium)
                .font(.custom("Fustat", size: 14).weight(.medium))
                .frame(minHeight: 40)
                .background(OMSTokens.Color.surface)
                .foregroundStyle(OMSTokens.Color.slate900)
                .overlay(
                    RoundedRectangle(cornerRadius: OMSTokens.Radius.input)
                        .stroke(borderColor, lineWidth: 1)
                )
                .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.input))
                .opacity(isDisabled ? 0.5 : 1)

            if let message = messageText {{
                OMSLabel(message, variant: messageIsError ? .error : .caption)
            }}
        }}
    }}

    private var isDisabled: Bool {{
        if case .disabled = state {{ return true }}
        return false
    }}

    private var messageText: String? {{
        if case .error(let message) = state {{ return message }}
        return helperText
    }}

    private var messageIsError: Bool {{
        if case .error = state {{ return true }}
        return false
    }}

    private var borderColor: SwiftUI.Color {{
        switch state {{
        case .normal:
            return OMSTokens.Color.slate300
        case .error:
            return OMSTokens.Color.slate300
        case .disabled:
            return OMSTokens.Color.slate300
        }}
    }}
}}

public struct OMSDropdown<Option: Hashable & CustomStringConvertible>: View {{
    private let title: String
    private let options: [Option]
    @Binding private var selection: Option

    public init(_ title: String, selection: Binding<Option>, options: [Option]) {{
        self.title = title
        self._selection = selection
        self.options = options
    }}

    public var body: some View {{
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.xsmall) {{
            OMSLabel(title, variant: .caption)
            Picker(title, selection: $selection) {{
                ForEach(options, id: \\.self) {{ option in
                    Text(option.description).tag(option)
                }}
            }}
            .pickerStyle(.menu)
            .frame(maxWidth: .infinity, alignment: .leading)
            .padding(.horizontal, OMSTokens.Spacing.medium)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .frame(minHeight: 40)
            .background(OMSTokens.Color.surface)
            .overlay(
                RoundedRectangle(cornerRadius: OMSTokens.Radius.input)
                    .stroke(OMSTokens.Color.slate300, lineWidth: 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.input))
        }}
    }}
}}

public struct OMSToggle: View {{
    private let title: String
    @Binding private var isOn: Bool

    public init(_ title: String, isOn: Binding<Bool>) {{
        self.title = title
        self._isOn = isOn
    }}

    public var body: some View {{
        Toggle(title, isOn: $isOn)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .foregroundStyle(OMSTokens.Color.slate900)
            .tint(OMSTokens.Color.purple500)
    }}
}}

public struct OMSBadge: View {{
    private let text: String
    private let variant: OMSBadgeVariant

    public init(_ text: String, variant: OMSBadgeVariant = .neutral) {{
        self.text = text
        self.variant = variant
    }}

    public var body: some View {{
        Text(text)
            .font(.custom("Fustat", size: 14).weight(.medium))
            .foregroundStyle(foregroundColor)
            .padding(.horizontal, OMSTokens.Spacing.small)
            .padding(.vertical, OMSTokens.Spacing.xsmall)
            .background(backgroundColor)
            .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.badge).stroke(borderColor, lineWidth: 0.5))
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.badge))
    }}

    private var backgroundColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple50
        case .neutral:
            return OMSTokens.Color.slate50
        case .success:
            return OMSTokens.Color.emerald50
        case .warning:
            return OMSTokens.Color.orange50
        case .danger:
            return OMSTokens.Color.red50
        }}
    }}

    private var foregroundColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple700
        case .neutral:
            return OMSTokens.Color.slate900
        case .success:
            return OMSTokens.Color.emerald700
        case .warning:
            return OMSTokens.Color.amber700
        case .danger:
            return OMSTokens.Color.red700
        }}
    }}

    private var borderColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple200
        case .neutral:
            return OMSTokens.Color.slate300
        case .success:
            return OMSTokens.Color.emerald200
        case .warning:
            return OMSTokens.Color.orange200
        case .danger:
            return OMSTokens.Color.red200
        }}
    }}
}}

public struct OMSAlert: View {{
    private let title: String
    private let message: String
    private let variant: OMSAlertVariant

    public init(_ title: String, message: String, variant: OMSAlertVariant = .info) {{
        self.title = title
        self.message = message
        self.variant = variant
    }}

    public var body: some View {{
        HStack(alignment: .top, spacing: OMSTokens.Spacing.medium) {{
            Image(systemName: iconName)
                .font(.system(size: 16, weight: .medium))
                .foregroundStyle(accentColor)
            VStack(alignment: .leading, spacing: OMSTokens.Spacing.small) {{
                Text(title)
                    .font(.custom("Fustat", size: 14).weight(.bold))
                    .foregroundStyle(OMSTokens.Color.slate950)
                Text(message)
                    .font(.custom("Fustat", size: 13).weight(.medium))
                    .foregroundStyle(accentColor)
            }}
        }}
        .padding(OMSTokens.Spacing.large)
        .frame(maxWidth: .infinity, alignment: .leading)
        .background(backgroundColor)
        .overlay(RoundedRectangle(cornerRadius: OMSTokens.Radius.card).stroke(borderColor, lineWidth: 1))
        .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.card))
    }}

    private var iconName: String {{
        switch variant {{
        case .info:
            return "info.circle"
        case .success:
            return "checkmark.circle"
        case .warning:
            return "exclamationmark.triangle"
        case .danger:
            return "xmark.octagon"
        }}
    }}

    private var backgroundColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple50
        case .success:
            return OMSTokens.Color.emerald50
        case .warning:
            return OMSTokens.Color.orange50
        case .danger:
            return OMSTokens.Color.red50
        }}
    }}

    private var borderColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple200
        case .success:
            return OMSTokens.Color.emerald200
        case .warning:
            return OMSTokens.Color.orange200
        case .danger:
            return OMSTokens.Color.red200
        }}
    }}

    private var accentColor: SwiftUI.Color {{
        switch variant {{
        case .info:
            return OMSTokens.Color.purple700
        case .success:
            return OMSTokens.Color.emerald700
        case .warning:
            return OMSTokens.Color.amber700
        case .danger:
            return OMSTokens.Color.red700
        }}
    }}
}}

public struct OMSCard<Content: View>: View {{
    private let content: () -> Content

    public init(@ViewBuilder content: @escaping () -> Content) {{
        self.content = content
    }}

    public var body: some View {{
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.medium, content: content)
            .padding(OMSTokens.Spacing.large)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(OMSTokens.Color.surface)
            .overlay(
                RoundedRectangle(cornerRadius: OMSTokens.Radius.card)
                    .stroke(OMSTokens.Color.slate200, lineWidth: 1)
            )
            .clipShape(RoundedRectangle(cornerRadius: OMSTokens.Radius.card))
    }}
}}
"""


def kotlin(package_name: str) -> str:
    return f"""// {GENERATED_HEADER}
@file:Suppress("FunctionName")

package {package_name}

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.defaultMinSize
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.heightIn
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.DropdownMenuItem
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.ExposedDropdownMenuBox
import androidx.compose.material3.ExposedDropdownMenuDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.MenuAnchorType
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.OutlinedTextFieldDefaults
import androidx.compose.material3.Surface
import androidx.compose.material3.Switch
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

enum class OMSButtonVariant {{ Primary, Secondary, DangerPrimary, DangerSecondary }}
enum class OMSButtonSize {{ Small, Medium, Large }}
enum class OMSLabelVariant {{ Title, Body, Caption, Subtle, Error }}
enum class OMSBadgeVariant {{ Info, Neutral, Success, Warning, Danger }}
enum class OMSAlertVariant {{ Info, Success, Warning, Danger }}

sealed interface OMSFieldState {{
    data object Normal : OMSFieldState
    data class Error(val message: String) : OMSFieldState
    data object Disabled : OMSFieldState
}}

object OMSColors {{
    val Slate50 = Color(0xFFF6F6FC)
    val Slate100 = Color(0xFFEEF0F9)
    val Slate200 = Color(0xFFDFE3F0)
    val Slate300 = Color(0xFFC8CFE1)
    val Slate400 = Color(0xFF929EBA)
    val Slate500 = Color(0xFF64708F)
    val Slate800 = Color(0xFF222744)
    val Slate900 = Color(0xFF141635)
    val Slate950 = Color(0xFF090624)
    val Purple50 = Color(0xFFF6F3FB)
    val Purple100 = Color(0xFFEAE4F5)
    val Purple200 = Color(0xFFD5C4F2)
    val Purple300 = Color(0xFFB78EEF)
    val Purple500 = Color(0xFF670DE5)
    val Purple700 = Color(0xFF400A8E)
    val Red50 = Color(0xFFFEF2F2)
    val Red100 = Color(0xFFFEE2E2)
    val Red200 = Color(0xFFFECACA)
    val Red400 = Color(0xFFF87171)
    val Red500 = Color(0xFFEF4444)
    val Red600 = Color(0xFFDC2626)
    val Red700 = Color(0xFFB91C1C)
    val Red800 = Color(0xFF991B1B)
    val Emerald50 = Color(0xFFECFDF5)
    val Emerald200 = Color(0xFFA7F3D0)
    val Emerald700 = Color(0xFF047857)
    val Orange50 = Color(0xFFFFF7ED)
    val Orange200 = Color(0xFFFED7AA)
    val Amber700 = Color(0xFFB45309)
    val Surface = Color.White
    val Canvas = Slate50
    val Ink = Slate900
    val MutedInk = Slate500
    val Border = Slate300
    val Brand = Purple500
    val Success = Emerald700
    val Warning = Amber700
    val Danger = Red700
}}

object OMSSpacing {{
    val XSmall = 4.dp
    val Small = 8.dp
    val Medium = 12.dp
    val Large = 16.dp
    val XLarge = 24.dp
}}

object OMSRadius {{
    val Button = 8.dp
    val ButtonLarge = 12.dp
    val Input = 12.dp
    val Badge = 16.dp
    val Card = 24.dp
}}

@Composable
fun OMSButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    variant: OMSButtonVariant = OMSButtonVariant.Primary,
    size: OMSButtonSize = OMSButtonSize.Medium,
    enabled: Boolean = true,
    fillsWidth: Boolean = false,
) {{
    val height = when (size) {{
        OMSButtonSize.Small -> 30.dp
        OMSButtonSize.Medium -> 32.dp
        OMSButtonSize.Large -> 40.dp
    }}

    val contentPadding = when (size) {{
        OMSButtonSize.Small -> PaddingValues(horizontal = 8.dp)
        OMSButtonSize.Medium -> PaddingValues(horizontal = 12.dp)
        OMSButtonSize.Large -> PaddingValues(horizontal = 12.dp)
    }}

    val buttonModifier = modifier
        .heightIn(min = height)
        .then(if (fillsWidth) Modifier.fillMaxWidth() else Modifier)

    val cornerRadius = if (size == OMSButtonSize.Large) OMSRadius.ButtonLarge else OMSRadius.Button

    Button(
        onClick = onClick,
        enabled = enabled,
        modifier = buttonModifier,
        shape = RoundedCornerShape(cornerRadius),
        colors = ButtonDefaults.buttonColors(
            containerColor = when (variant) {{
                OMSButtonVariant.Primary -> OMSColors.Slate950
                OMSButtonVariant.Secondary -> OMSColors.Surface
                OMSButtonVariant.DangerPrimary -> OMSColors.Red600
                OMSButtonVariant.DangerSecondary -> OMSColors.Surface
            }},
            contentColor = when (variant) {{
                OMSButtonVariant.Primary, OMSButtonVariant.DangerPrimary -> Color.White
                OMSButtonVariant.Secondary, OMSButtonVariant.DangerSecondary -> OMSColors.Slate950
            }},
        ),
        border = when (variant) {{
            OMSButtonVariant.Primary, OMSButtonVariant.DangerPrimary -> null
            OMSButtonVariant.Secondary -> BorderStroke(1.dp, OMSColors.Slate500)
            OMSButtonVariant.DangerSecondary -> BorderStroke(1.dp, OMSColors.Red600)
        }},
        contentPadding = contentPadding,
    ) {{
        Text(text = text, fontWeight = FontWeight.SemiBold)
    }}
}}

@Composable
fun OMSIconButton(
    imageVector: ImageVector,
    contentDescription: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    size: Dp = 40.dp,
) {{
    Surface(
        onClick = onClick,
        modifier = modifier.size(size),
        shape = RoundedCornerShape(OMSRadius.ButtonLarge),
        color = OMSColors.Surface,
        contentColor = OMSColors.Slate950,
        border = BorderStroke(1.dp, OMSColors.Slate300),
    ) {{
        Column(
            modifier = Modifier.fillMaxSize(),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.Center,
        ) {{
            Icon(imageVector = imageVector, contentDescription = contentDescription)
        }}
    }}
}}

@Composable
fun OMSIconLabelButton(
    imageVector: ImageVector,
    text: String,
    contentDescription: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
) {{
    Column(
        modifier = modifier,
        horizontalAlignment = Alignment.CenterHorizontally,
        verticalArrangement = Arrangement.spacedBy(OMSSpacing.Small),
    ) {{
        OMSIconButton(
            imageVector = imageVector,
            contentDescription = contentDescription,
            onClick = onClick,
            size = 40.dp,
        )
        Text(
            text = text,
            color = OMSColors.Ink,
            style = MaterialTheme.typography.labelMedium,
            fontWeight = FontWeight.Medium,
        )
    }}
}}

@Composable
fun OMSLabel(
    text: String,
    modifier: Modifier = Modifier,
    variant: OMSLabelVariant = OMSLabelVariant.Body,
) {{
    Text(
        text = text,
        modifier = modifier,
        style = when (variant) {{
            OMSLabelVariant.Title -> MaterialTheme.typography.titleMedium
            OMSLabelVariant.Body -> MaterialTheme.typography.bodyMedium
            OMSLabelVariant.Caption -> MaterialTheme.typography.labelMedium
            OMSLabelVariant.Subtle -> MaterialTheme.typography.bodySmall
            OMSLabelVariant.Error -> MaterialTheme.typography.labelMedium
        }},
        color = when (variant) {{
            OMSLabelVariant.Title -> OMSColors.Slate950
            OMSLabelVariant.Body -> OMSColors.Slate900
            OMSLabelVariant.Caption, OMSLabelVariant.Subtle -> OMSColors.Slate500
            OMSLabelVariant.Error -> OMSColors.Red700
        }},
        fontWeight = if (variant == OMSLabelVariant.Title || variant == OMSLabelVariant.Error) {{
            FontWeight.Bold
        }} else {{
            FontWeight.Medium
        }},
    )
}}

@Composable
fun OMSInputField(
    value: String,
    onValueChange: (String) -> Unit,
    label: String,
    modifier: Modifier = Modifier,
    placeholder: String = "",
    helperText: String? = null,
    state: OMSFieldState = OMSFieldState.Normal,
) {{
    val isError = state is OMSFieldState.Error
    val enabled = state !is OMSFieldState.Disabled
    val supportingText = if (state is OMSFieldState.Error) state.message else helperText

    OutlinedTextField(
        value = value,
        onValueChange = onValueChange,
        modifier = modifier.fillMaxWidth(),
        enabled = enabled,
        isError = isError,
        singleLine = true,
        label = {{ Text(label) }},
        placeholder = {{ Text(placeholder) }},
        supportingText = supportingText?.let {{ message ->
            {{ OMSLabel(message, variant = if (isError) OMSLabelVariant.Error else OMSLabelVariant.Caption) }}
        }},
        shape = RoundedCornerShape(OMSRadius.Input),
        colors = OutlinedTextFieldDefaults.colors(
            focusedBorderColor = OMSColors.Slate400,
            unfocusedBorderColor = OMSColors.Slate300,
            errorBorderColor = OMSColors.Slate300,
            focusedLabelColor = OMSColors.Slate900,
            errorLabelColor = OMSColors.Red700,
            focusedContainerColor = OMSColors.Surface,
            unfocusedContainerColor = OMSColors.Surface,
            disabledContainerColor = OMSColors.Surface,
            errorContainerColor = OMSColors.Surface,
        ),
    )
}}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun OMSDropdown(
    label: String,
    selected: String,
    options: List<String>,
    onSelected: (String) -> Unit,
    modifier: Modifier = Modifier,
) {{
    var expanded by remember {{ mutableStateOf(false) }}

    ExposedDropdownMenuBox(
        expanded = expanded,
        onExpandedChange = {{ expanded = it }},
        modifier = modifier.fillMaxWidth(),
    ) {{
        OutlinedTextField(
            value = selected,
            onValueChange = {{}},
            readOnly = true,
            singleLine = true,
            label = {{ Text(label) }},
            trailingIcon = {{ ExposedDropdownMenuDefaults.TrailingIcon(expanded = expanded) }},
            modifier = Modifier
                .menuAnchor(MenuAnchorType.PrimaryNotEditable)
                .fillMaxWidth(),
            shape = RoundedCornerShape(OMSRadius.Input),
            colors = OutlinedTextFieldDefaults.colors(
                focusedBorderColor = OMSColors.Slate400,
                unfocusedBorderColor = OMSColors.Slate300,
                focusedContainerColor = OMSColors.Surface,
                unfocusedContainerColor = OMSColors.Surface,
            ),
        )
        ExposedDropdownMenu(
            expanded = expanded,
            onDismissRequest = {{ expanded = false }},
        ) {{
            options.forEach {{ option ->
                DropdownMenuItem(
                    text = {{ Text(option) }},
                    onClick = {{
                        onSelected(option)
                        expanded = false
                    }},
                )
            }}
        }}
    }}
}}

@Composable
fun OMSToggle(
    text: String,
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    modifier: Modifier = Modifier,
) {{
    Row(
        modifier = modifier
            .fillMaxWidth()
            .defaultMinSize(minHeight = 44.dp),
        verticalAlignment = Alignment.CenterVertically,
        horizontalArrangement = Arrangement.SpaceBetween,
    ) {{
        OMSLabel(text, variant = OMSLabelVariant.Body)
        Switch(checked = checked, onCheckedChange = onCheckedChange)
    }}
}}

@Composable
fun OMSBadge(
    text: String,
    modifier: Modifier = Modifier,
    variant: OMSBadgeVariant = OMSBadgeVariant.Neutral,
) {{
    val color = when (variant) {{
        OMSBadgeVariant.Info -> OMSColors.Purple700
        OMSBadgeVariant.Neutral -> OMSColors.Slate900
        OMSBadgeVariant.Success -> OMSColors.Emerald700
        OMSBadgeVariant.Warning -> OMSColors.Amber700
        OMSBadgeVariant.Danger -> OMSColors.Red700
    }}

    val background = when (variant) {{
        OMSBadgeVariant.Info -> OMSColors.Purple50
        OMSBadgeVariant.Neutral -> OMSColors.Slate50
        OMSBadgeVariant.Success -> OMSColors.Emerald50
        OMSBadgeVariant.Warning -> OMSColors.Orange50
        OMSBadgeVariant.Danger -> OMSColors.Red50
    }}

    val border = when (variant) {{
        OMSBadgeVariant.Info -> OMSColors.Purple200
        OMSBadgeVariant.Neutral -> OMSColors.Slate300
        OMSBadgeVariant.Success -> OMSColors.Emerald200
        OMSBadgeVariant.Warning -> OMSColors.Orange200
        OMSBadgeVariant.Danger -> OMSColors.Red200
    }}

    Text(
        text = text,
        modifier = modifier
            .background(background, RoundedCornerShape(OMSRadius.Badge))
            .border(BorderStroke(0.5f.dp, border), RoundedCornerShape(OMSRadius.Badge))
            .padding(horizontal = OMSSpacing.Small, vertical = OMSSpacing.XSmall),
        color = color,
        style = MaterialTheme.typography.labelMedium,
        fontWeight = FontWeight.Medium,
    )
}}

@Composable
fun OMSAlert(
    title: String,
    message: String,
    modifier: Modifier = Modifier,
    variant: OMSAlertVariant = OMSAlertVariant.Info,
    icon: ImageVector? = null,
    contentDescription: String? = null,
) {{
    val colors = when (variant) {{
        OMSAlertVariant.Info -> Triple(OMSColors.Purple50, OMSColors.Purple200, OMSColors.Purple700)
        OMSAlertVariant.Success -> Triple(OMSColors.Emerald50, OMSColors.Emerald200, OMSColors.Emerald700)
        OMSAlertVariant.Warning -> Triple(OMSColors.Orange50, OMSColors.Orange200, OMSColors.Amber700)
        OMSAlertVariant.Danger -> Triple(OMSColors.Red50, OMSColors.Red200, OMSColors.Red700)
    }}

    Surface(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(OMSRadius.Card),
        color = colors.first,
        contentColor = colors.third,
        border = BorderStroke(1.dp, colors.second),
    ) {{
        Row(
            modifier = Modifier.padding(OMSSpacing.Large),
            horizontalArrangement = Arrangement.spacedBy(OMSSpacing.Medium),
            verticalAlignment = Alignment.Top,
        ) {{
            if (icon != null) {{
                Icon(imageVector = icon, contentDescription = contentDescription, modifier = Modifier.size(16.dp))
            }}
            Column(verticalArrangement = Arrangement.spacedBy(OMSSpacing.Small)) {{
                Text(
                    text = title,
                    color = OMSColors.Slate950,
                    style = MaterialTheme.typography.labelLarge,
                    fontWeight = FontWeight.Bold,
                )
                Text(
                    text = message,
                    color = colors.third,
                    style = MaterialTheme.typography.bodySmall,
                    fontWeight = FontWeight.Medium,
                )
            }}
        }}
    }}
}}

@Composable
fun OMSCard(
    modifier: Modifier = Modifier,
    content: @Composable () -> Unit,
) {{
    Card(
        modifier = modifier.fillMaxWidth(),
        colors = CardDefaults.cardColors(containerColor = OMSColors.Surface),
        border = BorderStroke(1.dp, OMSColors.Slate200),
        shape = RoundedCornerShape(OMSRadius.Card),
    ) {{
        Column(
            modifier = Modifier.padding(OMSSpacing.Large),
            verticalArrangement = Arrangement.spacedBy(OMSSpacing.Medium),
        ) {{
            content()
        }}
    }}
}}
"""


TYPESCRIPT = f"""// {GENERATED_HEADER}

export const omsTokens = {{
  color: {{
    slate50: "#F6F6FC",
    slate100: "#EEF0F9",
    slate200: "#DFE3F0",
    slate300: "#C8CFE1",
    slate400: "#929EBA",
    slate500: "#64708F",
    slate800: "#222744",
    slate900: "#141635",
    slate950: "#090624",
    purple50: "#F6F3FB",
    purple100: "#EAE4F5",
    purple200: "#D5C4F2",
    purple300: "#B78EEF",
    purple500: "#670DE5",
    purple700: "#400A8E",
    red50: "#FEF2F2",
    red100: "#FEE2E2",
    red200: "#FECACA",
    red400: "#F87171",
    red500: "#EF4444",
    red600: "#DC2626",
    red700: "#B91C1C",
    red800: "#991B1B",
    emerald50: "#ECFDF5",
    emerald200: "#A7F3D0",
    emerald700: "#047857",
    orange50: "#FFF7ED",
    orange200: "#FED7AA",
    amber700: "#B45309",
    surface: "#FFFFFF",
    page: "#F6F6FC",
    brand: "#670DE5",
    ink: "#141635",
    mutedInk: "#64708F",
    border: "#C8CFE1",
  }},
  radius: {{
    button: 8,
    buttonLarge: 12,
    input: 12,
    badge: 16,
    card: 24,
    pill: 999,
  }},
  spacing: {{
    xxsmall: 2,
    xsmall: 4,
    small: 8,
    medium: 12,
    large: 16,
    xlarge: 20,
    xxlarge: 24,
    xxxlarge: 32,
    section: 64,
  }},
  type: {{
    fontFamily: "'Fustat', 'Inter', system-ui, sans-serif",
    docFamily: "'Inter', system-ui, sans-serif",
    monoFamily: "'Geist Mono', 'JetBrains Mono', ui-monospace, monospace",
    lineHeight: 1.2,
    weightMedium: 500,
    weightBold: 700,
  }},
}} as const;

export const omsButtonRecipes = {{
  primary: {{
    background: omsTokens.color.slate950,
    color: omsTokens.color.surface,
    hoverBackground: omsTokens.color.slate800,
    activeBackground: omsTokens.color.purple700,
    borderColor: "transparent",
  }},
  secondary: {{
    background: "transparent",
    color: omsTokens.color.slate950,
    borderColor: omsTokens.color.slate500,
    hoverBorderColor: omsTokens.color.slate950,
    activeBackground: omsTokens.color.purple100,
    activeBorderColor: omsTokens.color.purple200,
  }},
  dangerPrimary: {{
    background: omsTokens.color.red600,
    color: omsTokens.color.surface,
    hoverBackground: omsTokens.color.red500,
    activeBackground: omsTokens.color.red800,
    borderColor: "transparent",
  }},
  dangerSecondary: {{
    background: "transparent",
    color: omsTokens.color.slate950,
    borderColor: omsTokens.color.red600,
    hoverBorderColor: omsTokens.color.red800,
    activeBackground: omsTokens.color.red100,
    activeBorderColor: omsTokens.color.red400,
  }},
}} as const;

export const omsComponentRecipes = {{
  button: {{
    sizes: {{
      small: {{ height: 30, paddingX: 8, radius: omsTokens.radius.button, fontSize: 12 }},
      medium: {{ height: 32, paddingX: 12, radius: omsTokens.radius.button, fontSize: 14 }},
      large: {{ height: 40, paddingX: 12, radius: omsTokens.radius.buttonLarge, fontSize: 16 }},
    }},
    variants: omsButtonRecipes,
    focusRing: `0 0 0 2px #fff, 0 0 0 4px ${{omsTokens.color.purple300}}`,
  }},
  input: {{
    height: 40,
    activeHeight: 44,
    radius: omsTokens.radius.input,
    background: omsTokens.color.surface,
    border: omsTokens.color.slate300,
    activeBorder: omsTokens.color.slate400,
    focusRing: "0 0 0 4px rgba(103, 13, 229, 0.15)",
    labelColor: omsTokens.color.slate900,
    helperColor: omsTokens.color.slate400,
    destructiveTextColor: omsTokens.color.red700,
  }},
  badge: {{
    radius: omsTokens.radius.badge,
    paddingY: 4,
    paddingX: 8,
    fontSize: 14,
    variants: {{
      info: {{ background: omsTokens.color.purple50, border: omsTokens.color.purple200, color: omsTokens.color.purple700 }},
      neutral: {{ background: omsTokens.color.slate50, border: omsTokens.color.slate300, color: omsTokens.color.slate900 }},
      success: {{ background: omsTokens.color.emerald50, border: omsTokens.color.emerald200, color: omsTokens.color.emerald700 }},
      warning: {{ background: omsTokens.color.orange50, border: omsTokens.color.orange200, color: omsTokens.color.amber700 }},
      danger: {{ background: omsTokens.color.red50, border: omsTokens.color.red200, color: omsTokens.color.red700 }},
    }},
  }},
  card: {{
    background: omsTokens.color.surface,
    border: omsTokens.color.slate200,
    radius: omsTokens.radius.card,
    padding: 24,
  }},
  alert: {{
    radius: 24,
    padding: 24,
    iconSize: 16,
    variants: {{
      info: {{ background: omsTokens.color.purple50, border: omsTokens.color.purple200, color: omsTokens.color.purple700 }},
      success: {{ background: omsTokens.color.emerald50, border: omsTokens.color.emerald200, color: omsTokens.color.emerald700 }},
      warning: {{ background: omsTokens.color.orange50, border: omsTokens.color.orange200, color: omsTokens.color.amber700 }},
      danger: {{ background: omsTokens.color.red50, border: omsTokens.color.red200, color: omsTokens.color.red700 }},
    }},
  }},
  iconButton: {{
    size: 40,
    radius: omsTokens.radius.buttonLarge,
    background: omsTokens.color.surface,
    border: omsTokens.color.slate300,
    color: omsTokens.color.slate950,
  }},
  statusBanner: {{
    height: 56,
    sandboxGradient: "linear-gradient(90deg, #EAE4F5 0%, #F6F3FB 100%)",
    liveGradient: "linear-gradient(90deg, #D5C8F4 0%, #D2D8F6 50%, #D0F5FD 100%)",
  }},
}} as const;

export const omsComponents = {{
  button: {{
    variants: ["primary", "secondary", "dangerPrimary", "dangerSecondary"],
    sizes: ["small", "medium", "large"],
  }},
  iconButton: {{
    variants: ["iconOnly"],
  }},
  inputField: {{
    states: ["normal", "active", "focus", "filled", "disabled", "destructive"],
  }},
  label: {{
    variants: ["title", "body", "caption", "subtle", "error"],
  }},
  dropdown: {{
    variants: ["default"],
  }},
  toggle: {{
    variants: ["default"],
  }},
  badge: {{
    variants: ["info", "neutral", "success", "warning", "danger"],
  }},
  card: {{
    variants: ["default"],
  }},
  alert: {{
    variants: ["info", "success", "warning", "danger"],
  }},
}} as const;

export type OMSButtonVariant = (typeof omsComponents.button.variants)[number];
export type OMSButtonSize = (typeof omsComponents.button.sizes)[number];
export type OMSLabelVariant = (typeof omsComponents.label.variants)[number];
export type OMSBadgeVariant = (typeof omsComponents.badge.variants)[number];
export type OMSAlertVariant = (typeof omsComponents.alert.variants)[number];
"""


SWIFT_EXAMPLE = """// Generated by design-architect.

import SwiftUI

@main
struct OMSDesignSystemExampleApp: App {
    var body: some Scene {
        WindowGroup {
            ComponentGallery()
        }
    }
}

private struct ComponentGallery: View {
    @State private var name = ""
    @State private var email = "person@example.com"
    @State private var selectedNetwork = "Polygon"
    @State private var notificationsEnabled = true

    private let networks = ["Polygon", "Ethereum", "Amoy"]

    var body: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: OMSTokens.Spacing.xlarge) {
                section("Buttons") {
                    VStack(alignment: .leading, spacing: OMSTokens.Spacing.medium) {
                        OMSButton("Primary", variant: .primary, action: {})
                        OMSButton("Secondary", variant: .secondary, action: {})
                        OMSButton("Danger primary", variant: .dangerPrimary, action: {})
                        OMSButton("Danger secondary", variant: .dangerSecondary, action: {})
                        OMSButton("Create deposit address", variant: .primary, size: .large, fillsWidth: true, action: {})
                        HStack(spacing: OMSTokens.Spacing.large) {
                            OMSIconButton(systemImage: "arrow.clockwise", accessibilityLabel: "Refresh", action: {})
                            OMSIconLabelButton(systemImage: "creditcard", text: "Payments", action: {})
                        }
                    }
                }

                section("Input Fields") {
                    VStack(spacing: OMSTokens.Spacing.large) {
                        OMSInputField("Name", text: $name, placeholder: "Ada Lovelace", helperText: "Used on wallet receipts.")
                        OMSInputField("Email", text: $email, state: .error("Enter a valid organization email."))
                    }
                }

                section("Labels") {
                    VStack(alignment: .leading, spacing: OMSTokens.Spacing.small) {
                        OMSLabel("Title label", variant: .title)
                        OMSLabel("Body label", variant: .body)
                        OMSLabel("Caption label", variant: .caption)
                        OMSLabel("Subtle label", variant: .subtle)
                        OMSLabel("Error label", variant: .error)
                    }
                }

                section("Dropdowns And Toggles") {
                    VStack(spacing: OMSTokens.Spacing.large) {
                        OMSDropdown("Network", selection: $selectedNetwork, options: networks)
                        OMSToggle("Transaction notifications", isOn: $notificationsEnabled)
                    }
                }

                section("Badges And Cards") {
                    VStack(alignment: .leading, spacing: OMSTokens.Spacing.medium) {
                        HStack {
                            OMSBadge("Info", variant: .info)
                            OMSBadge("Neutral")
                            OMSBadge("Success", variant: .success)
                            OMSBadge("Warning", variant: .warning)
                            OMSBadge("Danger", variant: .danger)
                        }
                        OMSCard {
                            OMSLabel("Wallet Limit", variant: .title)
                            OMSLabel("Daily transaction controls share the same generated spacing, colors, and typography.")
                            OMSButton("Review", variant: .primary, action: {})
                        }
                        OMSAlert(
                            "Sandbox mode",
                            message: "You are testing OMSX capabilities in a sandbox environment",
                            variant: .info
                        )
                    }
                }
            }
            .padding(OMSTokens.Spacing.xlarge)
        }
        .background(OMSTokens.Color.page)
    }

    @ViewBuilder
    private func section<Content: View>(_ title: String, @ViewBuilder content: () -> Content) -> some View {
        VStack(alignment: .leading, spacing: OMSTokens.Spacing.medium) {
            OMSLabel(title, variant: .title)
            content()
        }
    }
}
"""


IOS_INFO_PLIST = """<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleDevelopmentRegion</key>
    <string>$(DEVELOPMENT_LANGUAGE)</string>
    <key>CFBundleExecutable</key>
    <string>$(EXECUTABLE_NAME)</string>
    <key>CFBundleIdentifier</key>
    <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
    <key>CFBundleInfoDictionaryVersion</key>
    <string>6.0</string>
    <key>CFBundleName</key>
    <string>$(PRODUCT_NAME)</string>
    <key>CFBundlePackageType</key>
    <string>$(PRODUCT_BUNDLE_PACKAGE_TYPE)</string>
    <key>CFBundleShortVersionString</key>
    <string>$(MARKETING_VERSION)</string>
    <key>CFBundleVersion</key>
    <string>$(CURRENT_PROJECT_VERSION)</string>
    <key>UILaunchScreen</key>
    <dict/>
    <key>UISupportedInterfaceOrientations</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
    <key>UISupportedInterfaceOrientations~ipad</key>
    <array>
        <string>UIInterfaceOrientationPortrait</string>
        <string>UIInterfaceOrientationPortraitUpsideDown</string>
        <string>UIInterfaceOrientationLandscapeLeft</string>
        <string>UIInterfaceOrientationLandscapeRight</string>
    </array>
</dict>
</plist>
"""


XCODE_PROJECT = """// !$*UTF8*$!
{
    archiveVersion = 1;
    classes = {
    };
    objectVersion = 56;
    objects = {

/* Begin PBXBuildFile section */
        8F4B5A7D2B3D4D1A91A00001 /* OMSDesignSystemExampleApp.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8F4B5A7D2B3D4D1A91A00011 /* OMSDesignSystemExampleApp.swift */; };
        8F4B5A7D2B3D4D1A91A00002 /* styling.gen.swift in Sources */ = {isa = PBXBuildFile; fileRef = 8F4B5A7D2B3D4D1A91A00012 /* styling.gen.swift */; };
/* End PBXBuildFile section */

/* Begin PBXFileReference section */
        8F4B5A7D2B3D4D1A91A00010 /* OMSDesignSystemSwiftExample.app */ = {isa = PBXFileReference; explicitFileType = wrapper.application; includeInIndex = 0; path = OMSDesignSystemSwiftExample.app; sourceTree = BUILT_PRODUCTS_DIR; };
        8F4B5A7D2B3D4D1A91A00011 /* OMSDesignSystemExampleApp.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = OMSDesignSystemExampleApp.swift; sourceTree = "<group>"; };
        8F4B5A7D2B3D4D1A91A00012 /* styling.gen.swift */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.swift; path = styling.gen.swift; sourceTree = "<group>"; };
        8F4B5A7D2B3D4D1A91A00013 /* Info.plist */ = {isa = PBXFileReference; lastKnownFileType = text.plist.xml; path = Info.plist; sourceTree = "<group>"; };
/* End PBXFileReference section */

/* Begin PBXFrameworksBuildPhase section */
        8F4B5A7D2B3D4D1A91A00020 /* Frameworks */ = {
            isa = PBXFrameworksBuildPhase;
            buildActionMask = 2147483647;
            files = (
            );
            runOnlyForDeploymentPostprocessing = 0;
        };
/* End PBXFrameworksBuildPhase section */

/* Begin PBXGroup section */
        8F4B5A7D2B3D4D1A91A00030 = {
            isa = PBXGroup;
            children = (
                8F4B5A7D2B3D4D1A91A00031 /* OMSDesignSystemSwiftExample */,
                8F4B5A7D2B3D4D1A91A00032 /* Products */,
            );
            sourceTree = "<group>";
        };
        8F4B5A7D2B3D4D1A91A00031 /* OMSDesignSystemSwiftExample */ = {
            isa = PBXGroup;
            children = (
                8F4B5A7D2B3D4D1A91A00011 /* OMSDesignSystemExampleApp.swift */,
                8F4B5A7D2B3D4D1A91A00012 /* styling.gen.swift */,
                8F4B5A7D2B3D4D1A91A00013 /* Info.plist */,
            );
            path = OMSDesignSystemSwiftExample;
            sourceTree = "<group>";
        };
        8F4B5A7D2B3D4D1A91A00032 /* Products */ = {
            isa = PBXGroup;
            children = (
                8F4B5A7D2B3D4D1A91A00010 /* OMSDesignSystemSwiftExample.app */,
            );
            name = Products;
            sourceTree = "<group>";
        };
/* End PBXGroup section */

/* Begin PBXNativeTarget section */
        8F4B5A7D2B3D4D1A91A00040 /* OMSDesignSystemSwiftExample */ = {
            isa = PBXNativeTarget;
            buildConfigurationList = 8F4B5A7D2B3D4D1A91A00070 /* Build configuration list for PBXNativeTarget "OMSDesignSystemSwiftExample" */;
            buildPhases = (
                8F4B5A7D2B3D4D1A91A00021 /* Sources */,
                8F4B5A7D2B3D4D1A91A00020 /* Frameworks */,
                8F4B5A7D2B3D4D1A91A00022 /* Resources */,
            );
            buildRules = (
            );
            dependencies = (
            );
            name = OMSDesignSystemSwiftExample;
            productName = OMSDesignSystemSwiftExample;
            productReference = 8F4B5A7D2B3D4D1A91A00010 /* OMSDesignSystemSwiftExample.app */;
            productType = "com.apple.product-type.application";
        };
/* End PBXNativeTarget section */

/* Begin PBXProject section */
        8F4B5A7D2B3D4D1A91A00050 /* Project object */ = {
            isa = PBXProject;
            attributes = {
                BuildIndependentTargetsInParallel = 1;
                LastSwiftUpdateCheck = 1500;
                LastUpgradeCheck = 1500;
                TargetAttributes = {
                    8F4B5A7D2B3D4D1A91A00040 = {
                        CreatedOnToolsVersion = 15.0;
                    };
                };
            };
            buildConfigurationList = 8F4B5A7D2B3D4D1A91A00060 /* Build configuration list for PBXProject "OMSDesignSystemSwiftExample" */;
            compatibilityVersion = "Xcode 14.0";
            developmentRegion = en;
            hasScannedForEncodings = 0;
            knownRegions = (
                en,
                Base,
            );
            mainGroup = 8F4B5A7D2B3D4D1A91A00030;
            productRefGroup = 8F4B5A7D2B3D4D1A91A00032 /* Products */;
            projectDirPath = "";
            projectRoot = "";
            targets = (
                8F4B5A7D2B3D4D1A91A00040 /* OMSDesignSystemSwiftExample */,
            );
        };
/* End PBXProject section */

/* Begin PBXResourcesBuildPhase section */
        8F4B5A7D2B3D4D1A91A00022 /* Resources */ = {
            isa = PBXResourcesBuildPhase;
            buildActionMask = 2147483647;
            files = (
            );
            runOnlyForDeploymentPostprocessing = 0;
        };
/* End PBXResourcesBuildPhase section */

/* Begin PBXSourcesBuildPhase section */
        8F4B5A7D2B3D4D1A91A00021 /* Sources */ = {
            isa = PBXSourcesBuildPhase;
            buildActionMask = 2147483647;
            files = (
                8F4B5A7D2B3D4D1A91A00001 /* OMSDesignSystemExampleApp.swift in Sources */,
                8F4B5A7D2B3D4D1A91A00002 /* styling.gen.swift in Sources */,
            );
            runOnlyForDeploymentPostprocessing = 0;
        };
/* End PBXSourcesBuildPhase section */

/* Begin XCBuildConfiguration section */
        8F4B5A7D2B3D4D1A91A00061 /* Debug */ = {
            isa = XCBuildConfiguration;
            buildSettings = {
                ALWAYS_SEARCH_USER_PATHS = NO;
                CLANG_ANALYZER_NONNULL = YES;
                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
                CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
                CLANG_ENABLE_MODULES = YES;
                CLANG_ENABLE_OBJC_ARC = YES;
                CLANG_ENABLE_OBJC_WEAK = YES;
                CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
                CLANG_WARN_BOOL_CONVERSION = YES;
                CLANG_WARN_COMMA = YES;
                CLANG_WARN_CONSTANT_CONVERSION = YES;
                CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
                CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
                CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
                CLANG_WARN_EMPTY_BODY = YES;
                CLANG_WARN_ENUM_CONVERSION = YES;
                CLANG_WARN_INFINITE_RECURSION = YES;
                CLANG_WARN_INT_CONVERSION = YES;
                CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
                CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
                CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
                CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
                CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
                CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
                CLANG_WARN_STRICT_PROTOTYPES = YES;
                CLANG_WARN_SUSPICIOUS_MOVE = YES;
                CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
                CLANG_WARN_UNREACHABLE_CODE = YES;
                CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
                COPY_PHASE_STRIP = NO;
                DEBUG_INFORMATION_FORMAT = dwarf;
                ENABLE_STRICT_OBJC_MSGSEND = YES;
                ENABLE_TESTABILITY = YES;
                GCC_C_LANGUAGE_STANDARD = gnu17;
                GCC_DYNAMIC_NO_PIC = NO;
                GCC_NO_COMMON_BLOCKS = YES;
                GCC_OPTIMIZATION_LEVEL = 0;
                GCC_PREPROCESSOR_DEFINITIONS = (
                    "DEBUG=1",
                    "$(inherited)",
                );
                GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
                GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
                GCC_WARN_UNDECLARED_SELECTOR = YES;
                GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
                GCC_WARN_UNUSED_FUNCTION = YES;
                GCC_WARN_UNUSED_VARIABLE = YES;
                IPHONEOS_DEPLOYMENT_TARGET = 16.0;
                SDKROOT = iphoneos;
                SWIFT_ACTIVE_COMPILATION_CONDITIONS = DEBUG;
                SWIFT_OPTIMIZATION_LEVEL = "-Onone";
            };
            name = Debug;
        };
        8F4B5A7D2B3D4D1A91A00062 /* Release */ = {
            isa = XCBuildConfiguration;
            buildSettings = {
                ALWAYS_SEARCH_USER_PATHS = NO;
                CLANG_ANALYZER_NONNULL = YES;
                CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION = YES_AGGRESSIVE;
                CLANG_CXX_LANGUAGE_STANDARD = "gnu++20";
                CLANG_ENABLE_MODULES = YES;
                CLANG_ENABLE_OBJC_ARC = YES;
                CLANG_ENABLE_OBJC_WEAK = YES;
                CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING = YES;
                CLANG_WARN_BOOL_CONVERSION = YES;
                CLANG_WARN_COMMA = YES;
                CLANG_WARN_CONSTANT_CONVERSION = YES;
                CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS = YES;
                CLANG_WARN_DIRECT_OBJC_ISA_USAGE = YES_ERROR;
                CLANG_WARN_DOCUMENTATION_COMMENTS = YES;
                CLANG_WARN_EMPTY_BODY = YES;
                CLANG_WARN_ENUM_CONVERSION = YES;
                CLANG_WARN_INFINITE_RECURSION = YES;
                CLANG_WARN_INT_CONVERSION = YES;
                CLANG_WARN_NON_LITERAL_NULL_CONVERSION = YES;
                CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF = YES;
                CLANG_WARN_OBJC_LITERAL_CONVERSION = YES;
                CLANG_WARN_OBJC_ROOT_CLASS = YES_ERROR;
                CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER = YES;
                CLANG_WARN_RANGE_LOOP_ANALYSIS = YES;
                CLANG_WARN_STRICT_PROTOTYPES = YES;
                CLANG_WARN_SUSPICIOUS_MOVE = YES;
                CLANG_WARN_UNGUARDED_AVAILABILITY = YES_AGGRESSIVE;
                CLANG_WARN_UNREACHABLE_CODE = YES;
                CLANG_WARN__DUPLICATE_METHOD_MATCH = YES;
                COPY_PHASE_STRIP = NO;
                DEBUG_INFORMATION_FORMAT = "dwarf-with-dsym";
                ENABLE_NS_ASSERTIONS = NO;
                ENABLE_STRICT_OBJC_MSGSEND = YES;
                GCC_C_LANGUAGE_STANDARD = gnu17;
                GCC_NO_COMMON_BLOCKS = YES;
                GCC_WARN_64_TO_32_BIT_CONVERSION = YES;
                GCC_WARN_ABOUT_RETURN_TYPE = YES_ERROR;
                GCC_WARN_UNDECLARED_SELECTOR = YES;
                GCC_WARN_UNINITIALIZED_AUTOS = YES_AGGRESSIVE;
                GCC_WARN_UNUSED_FUNCTION = YES;
                GCC_WARN_UNUSED_VARIABLE = YES;
                IPHONEOS_DEPLOYMENT_TARGET = 16.0;
                SDKROOT = iphoneos;
                SWIFT_COMPILATION_MODE = wholemodule;
                VALIDATE_PRODUCT = YES;
            };
            name = Release;
        };
        8F4B5A7D2B3D4D1A91A00071 /* Debug */ = {
            isa = XCBuildConfiguration;
            buildSettings = {
                CODE_SIGN_STYLE = Automatic;
                CURRENT_PROJECT_VERSION = 1;
                GENERATE_INFOPLIST_FILE = NO;
                INFOPLIST_FILE = OMSDesignSystemSwiftExample/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = 16.0;
                LD_RUNPATH_SEARCH_PATHS = (
                    "$(inherited)",
                    "@executable_path/Frameworks",
                );
                MARKETING_VERSION = 1.0;
                PRODUCT_BUNDLE_IDENTIFIER = com.oms.designsystem.example;
                PRODUCT_NAME = "$(TARGET_NAME)";
                SWIFT_EMIT_LOC_STRINGS = YES;
                SWIFT_VERSION = 5.0;
                TARGETED_DEVICE_FAMILY = "1,2";
            };
            name = Debug;
        };
        8F4B5A7D2B3D4D1A91A00072 /* Release */ = {
            isa = XCBuildConfiguration;
            buildSettings = {
                CODE_SIGN_STYLE = Automatic;
                CURRENT_PROJECT_VERSION = 1;
                GENERATE_INFOPLIST_FILE = NO;
                INFOPLIST_FILE = OMSDesignSystemSwiftExample/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = 16.0;
                LD_RUNPATH_SEARCH_PATHS = (
                    "$(inherited)",
                    "@executable_path/Frameworks",
                );
                MARKETING_VERSION = 1.0;
                PRODUCT_BUNDLE_IDENTIFIER = com.oms.designsystem.example;
                PRODUCT_NAME = "$(TARGET_NAME)";
                SWIFT_EMIT_LOC_STRINGS = YES;
                SWIFT_VERSION = 5.0;
                TARGETED_DEVICE_FAMILY = "1,2";
            };
            name = Release;
        };
/* End XCBuildConfiguration section */

/* Begin XCConfigurationList section */
        8F4B5A7D2B3D4D1A91A00060 /* Build configuration list for PBXProject "OMSDesignSystemSwiftExample" */ = {
            isa = XCConfigurationList;
            buildConfigurations = (
                8F4B5A7D2B3D4D1A91A00061 /* Debug */,
                8F4B5A7D2B3D4D1A91A00062 /* Release */,
            );
            defaultConfigurationIsVisible = 0;
            defaultConfigurationName = Release;
        };
        8F4B5A7D2B3D4D1A91A00070 /* Build configuration list for PBXNativeTarget "OMSDesignSystemSwiftExample" */ = {
            isa = XCConfigurationList;
            buildConfigurations = (
                8F4B5A7D2B3D4D1A91A00071 /* Debug */,
                8F4B5A7D2B3D4D1A91A00072 /* Release */,
            );
            defaultConfigurationIsVisible = 0;
            defaultConfigurationName = Release;
        };
/* End XCConfigurationList section */
    };
    rootObject = 8F4B5A7D2B3D4D1A91A00050 /* Project object */;
}
"""


KOTLIN_EXAMPLE = """// Generated by design-architect.

package com.oms.designsystem.example

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Add
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.saveable.rememberSaveable
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.oms.designsystem.OMSAlert
import com.oms.designsystem.OMSBadge
import com.oms.designsystem.OMSBadgeVariant
import com.oms.designsystem.OMSButton
import com.oms.designsystem.OMSButtonSize
import com.oms.designsystem.OMSButtonVariant
import com.oms.designsystem.OMSCard
import com.oms.designsystem.OMSColors
import com.oms.designsystem.OMSDropdown
import com.oms.designsystem.OMSFieldState
import com.oms.designsystem.OMSIconButton
import com.oms.designsystem.OMSIconLabelButton
import com.oms.designsystem.OMSInputField
import com.oms.designsystem.OMSLabel
import com.oms.designsystem.OMSLabelVariant
import com.oms.designsystem.OMSSpacing
import com.oms.designsystem.OMSToggle

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme {
                ComponentGallery()
            }
        }
    }
}

@Composable
fun ComponentGallery() {
    var name by rememberSaveable { mutableStateOf("") }
    var email by rememberSaveable { mutableStateOf("person@example.com") }
    var selectedNetwork by rememberSaveable { mutableStateOf("Polygon") }
    var notificationsEnabled by rememberSaveable { mutableStateOf(true) }
    val networks = remember { listOf("Polygon", "Ethereum", "Amoy") }

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(OMSColors.Canvas)
            .verticalScroll(rememberScrollState())
            .padding(OMSSpacing.XLarge),
        verticalArrangement = Arrangement.spacedBy(OMSSpacing.XLarge),
    ) {
        ExampleSection("Buttons") {
            OMSButton("Primary", onClick = {}, variant = OMSButtonVariant.Primary)
            OMSButton("Secondary", onClick = {}, variant = OMSButtonVariant.Secondary)
            OMSButton("Danger primary", onClick = {}, variant = OMSButtonVariant.DangerPrimary)
            OMSButton("Danger secondary", onClick = {}, variant = OMSButtonVariant.DangerSecondary)
            OMSButton(
                text = "Create deposit address",
                onClick = {},
                variant = OMSButtonVariant.Primary,
                size = OMSButtonSize.Large,
                fillsWidth = true,
            )
            Row(horizontalArrangement = Arrangement.spacedBy(OMSSpacing.Large)) {
                OMSIconButton(
                    imageVector = Icons.Filled.Refresh,
                    contentDescription = "Refresh",
                    onClick = {},
                )
                OMSIconLabelButton(
                    imageVector = Icons.Filled.Add,
                    text = "Add",
                    contentDescription = "Add",
                    onClick = {},
                )
            }
        }

        ExampleSection("Input Fields") {
            OMSInputField(
                value = name,
                onValueChange = { name = it },
                label = "Name",
                placeholder = "Ada Lovelace",
                helperText = "Used on wallet receipts.",
            )
            OMSInputField(
                value = email,
                onValueChange = { email = it },
                label = "Email",
                state = OMSFieldState.Error("Enter a valid organization email."),
            )
        }

        ExampleSection("Labels") {
            OMSLabel("Title label", variant = OMSLabelVariant.Title)
            OMSLabel("Body label", variant = OMSLabelVariant.Body)
            OMSLabel("Caption label", variant = OMSLabelVariant.Caption)
            OMSLabel("Subtle label", variant = OMSLabelVariant.Subtle)
            OMSLabel("Error label", variant = OMSLabelVariant.Error)
        }

        ExampleSection("Dropdowns And Toggles") {
            OMSDropdown(
                label = "Network",
                selected = selectedNetwork,
                options = networks,
                onSelected = { selectedNetwork = it },
            )
            OMSToggle(
                text = "Transaction notifications",
                checked = notificationsEnabled,
                onCheckedChange = { notificationsEnabled = it },
            )
        }

        ExampleSection("Badges And Cards") {
            Row(horizontalArrangement = Arrangement.spacedBy(OMSSpacing.Small)) {
                OMSBadge("Info", variant = OMSBadgeVariant.Info)
                OMSBadge("Neutral")
                OMSBadge("Success", variant = OMSBadgeVariant.Success)
                OMSBadge("Warning", variant = OMSBadgeVariant.Warning)
                OMSBadge("Danger", variant = OMSBadgeVariant.Danger)
            }
            OMSCard {
                OMSLabel("Wallet Limit", variant = OMSLabelVariant.Title)
                OMSLabel("Daily transaction controls share the same generated spacing, colors, and typography.")
                OMSButton("Review", onClick = {}, variant = OMSButtonVariant.Primary)
            }
            OMSAlert(
                title = "Sandbox mode",
                message = "You are testing OMSX capabilities in a sandbox environment",
            )
        }
    }
}

@Composable
private fun ExampleSection(
    title: String,
    content: @Composable Column.() -> Unit,
) {
    Column(
        modifier = Modifier.fillMaxWidth(),
        verticalArrangement = Arrangement.spacedBy(OMSSpacing.Medium),
    ) {
        OMSLabel(title, variant = OMSLabelVariant.Title)
        content()
    }
    Spacer(Modifier.height(4.dp))
}
"""


KOTLIN_SETTINGS = """pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "OMSDesignSystemKotlinExample"
include(":app")
"""


KOTLIN_ROOT_BUILD = """plugins {
    id("com.android.application") version "8.7.3" apply false
    id("org.jetbrains.kotlin.android") version "2.0.21" apply false
}
"""


KOTLIN_APP_BUILD = """plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "com.oms.designsystem.example"
    compileSdk = 35

    defaultConfig {
        applicationId = "com.oms.designsystem.example"
        minSdk = 26
        targetSdk = 35
        versionCode = 1
        versionName = "1.0"
    }

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(platform("androidx.compose:compose-bom:2024.12.01"))
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.ui:ui-tooling-preview")
    debugImplementation("androidx.compose.ui:ui-tooling")
}
"""


ANDROID_MANIFEST = """<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <application
        android:label="OMS Design System"
        android:theme="@style/AppTheme">
        <activity
            android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
    </application>
</manifest>
"""


ANDROID_STYLES = """<resources>
    <style name="AppTheme" parent="android:style/Theme.Material.Light.NoActionBar" />
</resources>
"""


REACT_PACKAGE_JSON = """{
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite --host 0.0.0.0",
    "build": "tsc -b && vite build",
    "preview": "vite preview --host 0.0.0.0"
  },
  "dependencies": {
    "lucide-react": "^0.468.0",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  },
  "devDependencies": {
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@vitejs/plugin-react": "^4.3.4",
    "typescript": "^5.7.2",
    "vite": "^5.4.11"
  }
}
"""


REACT_TSCONFIG = """{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ES2020"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"],
  "references": [{ "path": "./tsconfig.node.json" }]
}
"""


REACT_TSCONFIG_NODE = """{
  "compilerOptions": {
    "composite": true,
    "skipLibCheck": true,
    "module": "ESNext",
    "moduleResolution": "Node",
    "allowSyntheticDefaultImports": true
  },
  "include": ["vite.config.ts"]
}
"""


REACT_VITE_CONFIG = """import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()],
});
"""


REACT_INDEX_HTML = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>OMS Design System</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
"""


REACT_MAIN = """// Generated by design-architect.

import { createRoot } from "react-dom/client";
import App from "./App";
import { omsTokens } from "./styling.gen";

document.body.style.margin = "0";
document.body.style.background = omsTokens.color.page;
document.body.style.fontFamily = omsTokens.type.fontFamily;

createRoot(document.getElementById("root")!).render(<App />);
"""


REACT_APP = """// Generated by design-architect.

import type { CSSProperties, ReactNode } from "react";
import { ChevronDown, CreditCard, Info, RefreshCcw } from "lucide-react";
import {
  omsButtonRecipes,
  omsComponentRecipes,
  omsTokens,
  type OMSAlertVariant,
  type OMSBadgeVariant,
  type OMSButtonSize,
  type OMSButtonVariant,
  type OMSLabelVariant,
} from "./styling.gen";

const appStyle: CSSProperties = {
  minHeight: "100vh",
  background: omsTokens.color.page,
  color: omsTokens.color.ink,
};

const galleryStyle: CSSProperties = {
  boxSizing: "border-box",
  width: "min(960px, 100%)",
  margin: "0 auto",
  padding: omsTokens.spacing.xxxlarge,
  display: "flex",
  flexDirection: "column",
  gap: omsTokens.spacing.xxxlarge,
};

const sectionStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: omsTokens.spacing.medium,
};

const stackStyle: CSSProperties = {
  display: "flex",
  flexDirection: "column",
  gap: omsTokens.spacing.medium,
  alignItems: "flex-start",
};

const rowStyle: CSSProperties = {
  display: "flex",
  flexWrap: "wrap",
  gap: omsTokens.spacing.small,
  alignItems: "center",
};

type StyleWithVars = CSSProperties & Record<`--${string}`, string | number | undefined>;

const interactionStyles = `
.oms-button {
  box-sizing: border-box;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  height: var(--oms-button-height);
  padding: 0 var(--oms-button-padding-x);
  border: 1px solid var(--oms-button-border);
  border-radius: var(--oms-button-radius);
  background-color: var(--oms-button-background);
  color: var(--oms-button-color);
  font-family: ${omsTokens.type.fontFamily};
  font-size: var(--oms-button-font-size);
  font-weight: ${omsTokens.type.weightBold};
  line-height: ${omsTokens.type.lineHeight};
  cursor: pointer;
  transition: background-color 120ms ease, border-color 120ms ease, box-shadow 120ms ease, color 120ms ease;
}

@media (hover: hover) and (pointer: fine) {
  .oms-button:hover:not(:disabled) {
    background-color: var(--oms-button-hover-background);
    border-color: var(--oms-button-hover-border);
  }
}

.oms-button:active:not(:disabled) {
  background-color: var(--oms-button-active-background);
  border-color: var(--oms-button-active-border);
}

.oms-button:focus-visible {
  outline: 0;
  box-shadow: var(--oms-focus-ring);
}

.oms-button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.oms-icon-button {
  box-sizing: border-box;
  width: var(--oms-icon-button-size);
  height: var(--oms-icon-button-size);
  display: inline-flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--oms-icon-button-border);
  border-radius: var(--oms-icon-button-radius);
  background-color: var(--oms-icon-button-background);
  color: var(--oms-icon-button-color);
  cursor: pointer;
  transition: background-color 120ms ease, border-color 120ms ease, box-shadow 120ms ease, color 120ms ease;
}

@media (hover: hover) and (pointer: fine) {
  .oms-icon-button:hover:not(:disabled) {
    border-color: var(--oms-icon-button-hover-border);
  }
}

.oms-icon-button:active:not(:disabled) {
  background-color: var(--oms-icon-button-active-background);
  border-color: var(--oms-icon-button-active-border);
  color: var(--oms-icon-button-active-color);
}

.oms-icon-button:focus-visible {
  outline: 0;
  box-shadow: var(--oms-focus-ring);
}

.oms-icon-button:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.oms-field-control {
  box-sizing: border-box;
  width: 100%;
  height: var(--oms-field-height);
  border: 1px solid var(--oms-field-border);
  border-radius: var(--oms-field-radius);
  background-color: var(--oms-field-background);
  color: ${omsTokens.color.slate900};
  padding: 0 var(--oms-field-padding-right) 0 var(--oms-field-padding-left);
  font-family: ${omsTokens.type.fontFamily};
  font-size: 14px;
  font-weight: ${omsTokens.type.weightMedium};
  line-height: ${omsTokens.type.lineHeight};
  transition: border-color 120ms ease, box-shadow 120ms ease;
}

.oms-field-control:focus {
  outline: 0;
}

@media (hover: hover) and (pointer: fine) {
  .oms-field-control:hover:not(:disabled) {
    border-color: var(--oms-field-active-border);
  }
}

.oms-field-control:focus-visible {
  border-color: var(--oms-field-active-border);
  box-shadow: var(--oms-field-focus-ring);
}

.oms-field-control:disabled {
  cursor: not-allowed;
  opacity: 0.5;
}

.oms-field-control::placeholder {
  color: ${omsTokens.color.slate400};
}
`;

function getButtonStyle(
  variant: OMSButtonVariant,
  size: OMSButtonSize,
  fillsWidth: boolean
): StyleWithVars {
  const variantRecipe = omsButtonRecipes[variant];
  const sizeRecipe = omsComponentRecipes.button.sizes[size];
  const hoverBackground =
    "hoverBackground" in variantRecipe ? variantRecipe.hoverBackground : variantRecipe.background;
  const hoverBorderColor =
    "hoverBorderColor" in variantRecipe ? variantRecipe.hoverBorderColor : variantRecipe.borderColor;
  const activeBorderColor =
    "activeBorderColor" in variantRecipe ? variantRecipe.activeBorderColor : variantRecipe.borderColor;

  return {
    width: fillsWidth ? "100%" : undefined,
    "--oms-button-height": `${sizeRecipe.height}px`,
    "--oms-button-padding-x": `${sizeRecipe.paddingX}px`,
    "--oms-button-radius": `${sizeRecipe.radius}px`,
    "--oms-button-font-size": `${sizeRecipe.fontSize}px`,
    "--oms-button-background": variantRecipe.background,
    "--oms-button-color": variantRecipe.color,
    "--oms-button-border": variantRecipe.borderColor,
    "--oms-button-hover-background": hoverBackground,
    "--oms-button-hover-border": hoverBorderColor,
    "--oms-button-active-background": variantRecipe.activeBackground,
    "--oms-button-active-border": activeBorderColor,
    "--oms-focus-ring": omsComponentRecipes.button.focusRing,
  };
}

const iconButtonStyle: StyleWithVars = {
  "--oms-icon-button-size": `${omsComponentRecipes.iconButton.size}px`,
  "--oms-icon-button-radius": `${omsComponentRecipes.iconButton.radius}px`,
  "--oms-icon-button-background": omsComponentRecipes.iconButton.background,
  "--oms-icon-button-border": omsComponentRecipes.iconButton.border,
  "--oms-icon-button-color": omsComponentRecipes.iconButton.color,
  "--oms-icon-button-hover-border": omsTokens.color.slate950,
  "--oms-icon-button-active-background": omsTokens.color.purple100,
  "--oms-icon-button-active-border": omsTokens.color.purple200,
  "--oms-icon-button-active-color": omsTokens.color.purple700,
  "--oms-focus-ring": omsComponentRecipes.button.focusRing,
};

const fieldControlStyle: StyleWithVars = {
  "--oms-field-height": `${omsComponentRecipes.input.height}px`,
  "--oms-field-radius": `${omsComponentRecipes.input.radius}px`,
  "--oms-field-background": omsComponentRecipes.input.background,
  "--oms-field-border": omsComponentRecipes.input.border,
  "--oms-field-active-border": omsComponentRecipes.input.activeBorder,
  "--oms-field-focus-ring": omsComponentRecipes.input.focusRing,
  "--oms-field-padding-left": `${omsTokens.spacing.medium}px`,
  "--oms-field-padding-right": `${omsTokens.spacing.medium}px`,
};

const dropdownFieldControlStyle: StyleWithVars = {
  ...fieldControlStyle,
  appearance: "none",
  "--oms-field-padding-right": `${omsTokens.spacing.xxxlarge}px`,
};

function OMSLabel({
  children,
  variant = "body",
}: {
  children: ReactNode;
  variant?: OMSLabelVariant;
}) {
  const styles: Record<OMSLabelVariant, CSSProperties> = {
    title: {
      fontSize: 24,
      fontWeight: omsTokens.type.weightBold,
      color: omsTokens.color.slate950,
      lineHeight: omsTokens.type.lineHeight,
    },
    body: {
      fontSize: 16,
      fontWeight: omsTokens.type.weightMedium,
      color: omsTokens.color.slate900,
      lineHeight: omsTokens.type.lineHeight,
    },
    caption: {
      fontSize: 14,
      fontWeight: omsTokens.type.weightMedium,
      color: omsTokens.color.slate500,
      lineHeight: omsTokens.type.lineHeight,
    },
    subtle: {
      fontSize: 12,
      fontWeight: omsTokens.type.weightMedium,
      color: omsTokens.color.slate500,
      lineHeight: omsTokens.type.lineHeight,
    },
    error: {
      fontSize: 14,
      fontWeight: omsTokens.type.weightMedium,
      color: omsTokens.color.red700,
      lineHeight: omsTokens.type.lineHeight,
    },
  };

  return <span style={styles[variant]}>{children}</span>;
}

function OMSButton({
  children,
  variant = "primary",
  size = "medium",
  fillsWidth = false,
}: {
  children: ReactNode;
  variant?: OMSButtonVariant;
  size?: OMSButtonSize;
  fillsWidth?: boolean;
}) {
  return (
    <button
      type="button"
      className="oms-button"
      style={getButtonStyle(variant, size, fillsWidth)}
    >
      {children}
    </button>
  );
}

function OMSIconButton({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <button
      type="button"
      aria-label={label}
      className="oms-icon-button"
      style={iconButtonStyle}
    >
      {children}
    </button>
  );
}

function OMSIconLabelButton({
  label,
  children,
}: {
  label: string;
  children: ReactNode;
}) {
  return (
    <span style={{ display: "inline-flex", flexDirection: "column", gap: omsTokens.spacing.small, alignItems: "center" }}>
      <OMSIconButton label={label}>{children}</OMSIconButton>
      <OMSLabel variant="subtle">{label}</OMSLabel>
    </span>
  );
}

function OMSInputField({
  label,
  placeholder,
  helper,
  error,
}: {
  label: string;
  placeholder?: string;
  helper?: string;
  error?: string;
}) {
  return (
    <label style={{ display: "flex", flexDirection: "column", gap: omsTokens.spacing.xsmall, width: "100%" }}>
      <OMSLabel variant={error ? "error" : "caption"}>{label}</OMSLabel>
      <input
        className="oms-field-control"
        placeholder={placeholder}
        defaultValue={error ? "person@example.com" : ""}
        style={fieldControlStyle}
      />
      {(helper || error) && <OMSLabel variant={error ? "error" : "caption"}>{error ?? helper}</OMSLabel>}
    </label>
  );
}

function OMSDropdown() {
  return (
    <label style={{ display: "flex", flexDirection: "column", gap: omsTokens.spacing.xsmall, width: "100%" }}>
      <OMSLabel variant="caption">Network</OMSLabel>
      <span style={{ position: "relative", width: "100%" }}>
        <select
          className="oms-field-control"
          defaultValue="Polygon"
          style={dropdownFieldControlStyle}
        >
          <option>Polygon</option>
          <option>Ethereum</option>
          <option>Amoy</option>
        </select>
        <ChevronDown
          aria-hidden="true"
          size={16}
          style={{
            position: "absolute",
            right: omsTokens.spacing.medium,
            top: 12,
            pointerEvents: "none",
            color: omsTokens.color.slate500,
          }}
        />
      </span>
    </label>
  );
}

function OMSBadge({
  children,
  variant = "neutral",
}: {
  children: ReactNode;
  variant?: OMSBadgeVariant;
}) {
  const recipe = omsComponentRecipes.badge.variants[variant];

  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        minHeight: 24,
        padding: `${omsComponentRecipes.badge.paddingY}px ${omsComponentRecipes.badge.paddingX}px`,
        borderRadius: omsComponentRecipes.badge.radius,
        border: `0.5px solid ${recipe.border}`,
        background: recipe.background,
        color: recipe.color,
        fontSize: omsComponentRecipes.badge.fontSize,
        fontWeight: omsTokens.type.weightMedium,
        lineHeight: omsTokens.type.lineHeight,
      }}
    >
      {children}
    </span>
  );
}

function OMSCard({ children }: { children: ReactNode }) {
  return (
    <div
      style={{
        width: "100%",
        boxSizing: "border-box",
        display: "flex",
        flexDirection: "column",
        gap: omsTokens.spacing.medium,
        padding: omsComponentRecipes.card.padding,
        borderRadius: omsComponentRecipes.card.radius,
        border: `1px solid ${omsComponentRecipes.card.border}`,
        background: omsComponentRecipes.card.background,
      }}
    >
      {children}
    </div>
  );
}

function OMSAlert({
  title,
  message,
  variant = "info",
}: {
  title: string;
  message: string;
  variant?: OMSAlertVariant;
}) {
  const recipe = omsComponentRecipes.alert.variants[variant];

  return (
    <div
      style={{
        width: "100%",
        boxSizing: "border-box",
        display: "flex",
        gap: omsTokens.spacing.medium,
        padding: omsComponentRecipes.alert.padding,
        borderRadius: omsComponentRecipes.alert.radius,
        border: `1px solid ${recipe.border}`,
        background: recipe.background,
        color: recipe.color,
      }}
    >
      <Info size={omsComponentRecipes.alert.iconSize} />
      <div style={{ display: "flex", flexDirection: "column", gap: omsTokens.spacing.small }}>
        <span
          style={{
            color: omsTokens.color.slate950,
            fontSize: 14,
            fontWeight: omsTokens.type.weightBold,
            lineHeight: omsTokens.type.lineHeight,
          }}
        >
          {title}
        </span>
        <OMSLabel variant="subtle">{message}</OMSLabel>
      </div>
    </div>
  );
}

function Section({
  title,
  children,
}: {
  title: string;
  children: ReactNode;
}) {
  return (
    <section style={sectionStyle}>
      <OMSLabel variant="title">{title}</OMSLabel>
      {children}
    </section>
  );
}

export default function App() {
  return (
    <>
      <style>{interactionStyles}</style>
      <main style={appStyle}>
        <div style={galleryStyle}>
          <Section title="Buttons">
            <div style={stackStyle}>
              <OMSButton>Primary</OMSButton>
              <OMSButton variant="secondary">Secondary</OMSButton>
              <OMSButton variant="dangerPrimary">Danger primary</OMSButton>
              <OMSButton variant="dangerSecondary">Danger secondary</OMSButton>
              <OMSButton size="large" fillsWidth>
                Create deposit address
              </OMSButton>
              <div style={rowStyle}>
                <OMSIconButton label="Refresh">
                  <RefreshCcw size={18} />
                </OMSIconButton>
                <OMSIconLabelButton label="Payments">
                  <CreditCard size={18} />
                </OMSIconLabelButton>
              </div>
            </div>
          </Section>

          <Section title="Input fields">
            <div style={{ ...stackStyle, width: "100%" }}>
              <OMSInputField label="Name" placeholder="Ada Lovelace" helper="Used on wallet receipts." />
              <OMSInputField label="Email" error="Enter a valid organization email." />
            </div>
          </Section>

          <Section title="Labels">
            <div style={stackStyle}>
              <OMSLabel variant="title">Title label</OMSLabel>
              <OMSLabel>Body label</OMSLabel>
              <OMSLabel variant="caption">Caption label</OMSLabel>
              <OMSLabel variant="subtle">Subtle label</OMSLabel>
              <OMSLabel variant="error">Error label</OMSLabel>
            </div>
          </Section>

          <Section title="Dropdowns and toggles">
            <div style={{ ...stackStyle, width: "100%" }}>
              <OMSDropdown />
              <label style={{ ...rowStyle, justifyContent: "space-between", width: "100%" }}>
                <OMSLabel>Transaction notifications</OMSLabel>
                <input type="checkbox" defaultChecked />
              </label>
            </div>
          </Section>

          <Section title="Badges and cards">
            <div style={stackStyle}>
              <div style={rowStyle}>
                <OMSBadge variant="info">Info</OMSBadge>
                <OMSBadge>Neutral</OMSBadge>
                <OMSBadge variant="success">Success</OMSBadge>
                <OMSBadge variant="warning">Warning</OMSBadge>
                <OMSBadge variant="danger">Danger</OMSBadge>
              </div>
              <OMSCard>
                <OMSLabel variant="title">Wallet limit</OMSLabel>
                <OMSLabel>Daily transaction controls share the same generated spacing, colors, and typography.</OMSLabel>
                <OMSButton>Review</OMSButton>
              </OMSCard>
              <OMSAlert
                title="Sandbox mode"
                message="You are testing OMSX capabilities in a sandbox environment"
              />
            </div>
          </Section>
        </div>
      </main>
    </>
  );
}

"""


def write_file(path: Path, content: str, check: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized = content.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != normalized:
            print(f"DIFF {path}")
            for line in difflib.unified_diff(
                current.splitlines(),
                normalized.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ):
                print(line)
            return False
        return True
    path.write_text(normalized)
    return True


def link_or_copy(source: Path, destination: Path, check: bool) -> bool:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if check:
        if destination.is_symlink() and destination.resolve() == source.resolve():
            return True
        if destination.exists() and destination.read_text() == source.read_text():
            return True
        print(f"DIFF {destination}")
        print(f"Expected symlink or copy of {source}")
        return False

    if destination.exists() or destination.is_symlink():
        destination.unlink()
    relative_source = os.path.relpath(source, start=destination.parent)
    try:
        destination.symlink_to(relative_source)
    except OSError:
        destination.write_text(source.read_text())
    return True


def generate(project_root: Path, package_name: str, check: bool) -> bool:
    project_root = project_root.resolve()
    swift_root = project_root / "styling.gen.swift"
    kotlin_root = project_root / "styling.gen.kt"
    ts_root = project_root / "styling.gen.ts"

    ok = True
    ok &= write_file(swift_root, SWIFT, check)
    ok &= write_file(kotlin_root, kotlin(package_name), check)
    ok &= write_file(ts_root, TYPESCRIPT, check)

    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_root", nargs="?", default=".", help="Project root to receive generated files.")
    parser.add_argument(
        "--kotlin-package",
        default="com.oms.designsystem",
        help="Package name for styling.gen.kt.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Print diffs and fail if generated files are stale.",
    )
    args = parser.parse_args()

    ok = generate(Path(args.project_root), args.kotlin_package, args.check)
    if args.check and not ok:
        return 1

    verb = "Checked" if args.check else "Generated"
    print(f"{verb} OMS SDK design system in {Path(args.project_root).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
