#!/usr/bin/env python3
"""Generate design-system components from a selected theme."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_HEADER = "Generated by design-architect. Do not edit manually."
SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
THEMES_ROOT = SKILL_ROOT / "themes"


COLOR_NAMES = {
    "black": "#000000",
    "white": "#FFFFFF",
    "gray-50": "#F9FAFB",
    "gray-100": "#F3F4F6",
    "gray-200": "#E5E7EB",
    "gray-300": "#D1D5DB",
    "gray-400": "#9CA3AF",
    "gray-500": "#6B7280",
    "gray-600": "#4B5563",
    "gray-900": "#111827",
    "gray-950": "#030712",
    "slate-50": "#F6F6FC",
    "slate-100": "#EEF0F7",
    "slate-200": "#DFE3F0",
    "slate-300": "#C8CFE1",
    "slate-400": "#929EBA",
    "slate-500": "#64708F",
    "slate-900": "#141635",
    "slate-950": "#090624",
    "purple-50": "#F5F2FA",
    "purple-100": "#EBE3F8",
    "purple-500": "#670DE5",
    "purple-700": "#400A8F",
    "red-50": "#FEF2F2",
    "red-100": "#FEE2E2",
    "red-500": "#EF4444",
    "red-600": "#DC2626",
    "red-700": "#B91C1C",
    "red-800": "#991B1B",
    "emerald-50": "#ECFDF5",
    "emerald-500": "#10B981",
    "emerald-700": "#047857",
    "orange-50": "#FFF7ED",
    "orange-500": "#F97316",
    "amber-700": "#B45309",
}

REQUIRED_COLOR_FIELDS = [
    ("Brand accent", "Brand purple"),
    "Primary CTA",
    "App shell/page background",
    "Text hierarchy",
    "Typography",
    "Icons",
    "Motion",
]

REQUIRED_COMPONENT_FIELDS = [
    "Buttons",
    "Inputs",
    "Dropdowns",
    "Labels",
    "Badges",
    "Alerts",
    "Cards and panels",
    "Icon buttons",
    "Status banner",
]


@dataclass(frozen=True)
class ThemeConfig:
    slug: str
    name: str
    description: str
    color_spec: str
    components: str


@dataclass(frozen=True)
class ThemeTokens:
    slug: str
    name: str
    description: str
    font_family: str
    page: str
    surface: str
    secondary_surface: str
    header: str
    header_border: str
    footer: str
    primary_text: str
    secondary_text: str
    placeholder_text: str
    border: str
    focus_ring: str
    brand: str
    primary_button: str
    primary_button_text: str
    secondary_button: str
    secondary_button_text: str
    danger: str
    danger_soft: str
    danger_text: str
    success: str
    success_soft: str
    warning: str
    warning_soft: str
    info: str
    info_soft: str
    uses_borders: bool


def parse_frontmatter(markdown: str, path: Path) -> dict[str, str]:
    if not markdown.startswith("---\n"):
        raise ValueError(f"{path} must start with YAML frontmatter.")
    end = markdown.find("\n---", 4)
    if end == -1:
        raise ValueError(f"{path} has unterminated YAML frontmatter.")

    values: dict[str, str] = {}
    for line in markdown[4:end].splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        values[key.strip()] = value.strip().strip('"')
    return values


def available_themes() -> list[str]:
    if not THEMES_ROOT.exists():
        return []
    return sorted(path.name for path in THEMES_ROOT.iterdir() if (path / "CONFIG.md").is_file())


def read_theme(slug: str) -> ThemeConfig:
    theme_dir = THEMES_ROOT / slug
    if not theme_dir.is_dir():
        choices = ", ".join(available_themes()) or "none"
        raise ValueError(f"Unknown theme '{slug}'. Available themes: {choices}.")

    config_path = theme_dir / "CONFIG.md"
    color_path = theme_dir / "COLOR_SPEC.md"
    components_path = theme_dir / "COMPONENTS.md"
    for path in (config_path, color_path, components_path):
        if not path.is_file():
            raise ValueError(f"Theme '{slug}' is missing {path.name}.")

    config_text = config_path.read_text()
    frontmatter = parse_frontmatter(config_text, config_path)
    missing_config = [field for field in ("name", "description") if not frontmatter.get(field)]
    if missing_config:
        raise ValueError(f"{config_path} is missing frontmatter fields: {', '.join(missing_config)}.")

    color_spec = color_path.read_text()
    components = components_path.read_text()
    validate_required_fields(color_path, color_spec, REQUIRED_COLOR_FIELDS)
    validate_required_fields(components_path, components, REQUIRED_COMPONENT_FIELDS)

    return ThemeConfig(
        slug=slug,
        name=frontmatter["name"],
        description=frontmatter["description"],
        color_spec=color_spec,
        components=components,
    )


def validate_required_fields(path: Path, text: str, fields: list[str | tuple[str, ...]]) -> None:
    missing: list[str] = []
    for field in fields:
        options = (field,) if isinstance(field, str) else field
        if not any(re.search(rf"(^|\n)\s*-\s*{re.escape(option)}\b", text, re.I) for option in options):
            missing.append(options[0])
    if missing:
        raise ValueError(f"{path} is missing required fields: {', '.join(missing)}.")


def bullet(text: str, field: str) -> str:
    match = re.search(rf"^\s*-\s*{re.escape(field)}[^:]*:\s*(.+)$", text, re.I | re.M)
    return match.group(1).strip() if match else ""


def hexes(text: str) -> list[str]:
    return [match.group(0) for match in re.finditer(r"#[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?", text)]


def color_name(text: str, default: str) -> str:
    lowered = text.lower()
    for name, value in sorted(COLOR_NAMES.items(), key=lambda item: -len(item[0])):
        if re.search(rf"\b{re.escape(name)}\b", lowered):
            return value
    return default


def first_color(text: str, default: str) -> str:
    found = hexes(text)
    if found:
        return found[0]
    return color_name(text, default)


def second_color(text: str, default: str) -> str:
    found = hexes(text)
    if len(found) > 1:
        return found[1]
    return default


def resolve_font(text: str) -> str:
    if re.search(r"\bRoboto\b", text, re.I):
        return "Roboto"
    if re.search(r"\bFustat\b", text, re.I):
        return "Fustat"
    return "system"


def extract_tokens(theme: ThemeConfig) -> ThemeTokens:
    color_spec = theme.color_spec
    components = theme.components
    all_text = f"{color_spec}\n{components}"

    brand_line = bullet(color_spec, "Brand accent") or bullet(color_spec, "Brand purple")
    primary_line = bullet(color_spec, "Primary CTA")
    page_line = bullet(color_spec, "App shell/page background")
    border_line = bullet(color_spec, "Borders") or bullet(color_spec, "Default border")
    header_line = bullet(color_spec, "Top headers")
    footer_line = bullet(color_spec, "Footers")
    text_line = bullet(color_spec, "Text hierarchy")
    typography_line = bullet(color_spec, "Typography")
    buttons_line = bullet(components, "Buttons")
    inputs_line = bullet(components, "Inputs")
    cards_line = bullet(components, "Cards and panels")

    text_colors = hexes(text_line)
    primary_text = text_colors[0] if len(text_colors) > 0 else color_name(text_line, "#111827")
    secondary_text = text_colors[1] if len(text_colors) > 1 else "#4B5563"
    placeholder_text = text_colors[2] if len(text_colors) > 2 else "#9CA3AF"

    page = first_color(page_line, "#FFFFFF")
    page_colors = hexes(page_line)
    surface = page_colors[1] if len(page_colors) > 1 else ("#FFFFFF" if page == "#FFFFFF" else page)
    secondary_surface = first_color(inputs_line, first_color(cards_line, second_color(page_line, surface)))

    uses_borders = not re.search(r"\bno border|do not use borders\b", all_text, re.I)
    border = first_color(border_line, "#D1D5DB")
    if not uses_borders and hexes(header_line):
        border = second_color(header_line, border)

    primary_button = first_color(primary_line, "#111827")
    primary_button_text = "#000000" if "black" in primary_line.lower() else "#FFFFFF"
    if len(hexes(primary_line)) > 1:
        primary_button_text = hexes(primary_line)[1]

    secondary_clause = re.search(r"Secondary\s+(?:is|uses)\s+([^.;]+)", buttons_line, re.I)
    secondary_text = secondary_text
    if secondary_clause:
        secondary_button = first_color(secondary_clause.group(1), secondary_surface)
        secondary_button_text = second_color(secondary_clause.group(1), primary_text)
    else:
        secondary_button = secondary_surface
        secondary_button_text = primary_text

    danger_clause = re.search(r"Danger primary\s+(?:is|uses)\s+([^.;]+)", buttons_line, re.I)
    danger = first_color(danger_clause.group(1), "#DC2626") if danger_clause else "#DC2626"
    danger_text = "#FFFFFF" if "white label" in buttons_line.lower() else "#B91C1C"
    if theme.slug == "dark":
        danger_text = "#FEE2E2"

    info = first_color(bullet(color_spec, "Semantic colors"), first_color(brand_line, "#E5E7EB"))
    success = "#047857" if theme.slug != "dark" else "#10B981"
    warning = "#B45309" if theme.slug != "dark" else "#F97316"

    return ThemeTokens(
        slug=theme.slug,
        name=theme.name,
        description=theme.description,
        font_family=resolve_font(typography_line),
        page=page,
        surface=surface,
        secondary_surface=secondary_surface,
        header=first_color(header_line, page),
        header_border=second_color(header_line, border),
        footer=first_color(footer_line, page),
        primary_text=primary_text,
        secondary_text=secondary_text,
        placeholder_text=placeholder_text,
        border=border,
        focus_ring=first_color(brand_line, border),
        brand=first_color(brand_line, "#E5E7EB"),
        primary_button=primary_button,
        primary_button_text=primary_button_text,
        secondary_button=secondary_button,
        secondary_button_text=secondary_button_text,
        danger=danger,
        danger_soft="#FEE2E2" if theme.slug == "dark" else "#FEF2F2",
        danger_text=danger_text,
        success=success,
        success_soft="#064E3B" if theme.slug == "dark" else "#ECFDF5",
        warning=warning,
        warning_soft="#78350F" if theme.slug == "dark" else "#FFF7ED",
        info=info,
        info_soft=secondary_surface if theme.slug == "dark" else ("#F3F4F6" if theme.slug == "light" else "#F5F2FA"),
        uses_borders=uses_borders,
    )


def swift(tokens: ThemeTokens) -> str:
    border_width = "1" if tokens.uses_borders else "0"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})
// swiftlint:disable all

import SwiftUI

private extension Color {{
    init(designHex hex: String) {{
        let value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let scanner = Scanner(string: value)
        var rgba: UInt64 = 0
        scanner.scanHexInt64(&rgba)

        let red: Double
        let green: Double
        let blue: Double
        let alpha: Double

        if value.count == 8 {{
            red = Double((rgba >> 24) & 0xff) / 255
            green = Double((rgba >> 16) & 0xff) / 255
            blue = Double((rgba >> 8) & 0xff) / 255
            alpha = Double(rgba & 0xff) / 255
        }} else {{
            red = Double((rgba >> 16) & 0xff) / 255
            green = Double((rgba >> 8) & 0xff) / 255
            blue = Double(rgba & 0xff) / 255
            alpha = 1
        }}

        self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }}
}}

public enum DesignTheme {{
    public static let id = "{tokens.slug}"
    public static let name = "{escape_swift(tokens.name)}"
    public static let description = "{escape_swift(tokens.description)}"
}}

public enum DesignTokens {{
    public enum Color {{
        public static let page = SwiftUI.Color(designHex: "{tokens.page}")
        public static let surface = SwiftUI.Color(designHex: "{tokens.surface}")
        public static let secondarySurface = SwiftUI.Color(designHex: "{tokens.secondary_surface}")
        public static let header = SwiftUI.Color(designHex: "{tokens.header}")
        public static let headerBorder = SwiftUI.Color(designHex: "{tokens.header_border}")
        public static let footer = SwiftUI.Color(designHex: "{tokens.footer}")
        public static let primaryText = SwiftUI.Color(designHex: "{tokens.primary_text}")
        public static let secondaryText = SwiftUI.Color(designHex: "{tokens.secondary_text}")
        public static let placeholderText = SwiftUI.Color(designHex: "{tokens.placeholder_text}")
        public static let border = SwiftUI.Color(designHex: "{tokens.border}")
        public static let focusRing = SwiftUI.Color(designHex: "{tokens.focus_ring}")
        public static let brand = SwiftUI.Color(designHex: "{tokens.brand}")
        public static let primaryButton = SwiftUI.Color(designHex: "{tokens.primary_button}")
        public static let primaryButtonText = SwiftUI.Color(designHex: "{tokens.primary_button_text}")
        public static let secondaryButton = SwiftUI.Color(designHex: "{tokens.secondary_button}")
        public static let secondaryButtonText = SwiftUI.Color(designHex: "{tokens.secondary_button_text}")
        public static let danger = SwiftUI.Color(designHex: "{tokens.danger}")
        public static let dangerSoft = SwiftUI.Color(designHex: "{tokens.danger_soft}")
        public static let dangerText = SwiftUI.Color(designHex: "{tokens.danger_text}")
        public static let success = SwiftUI.Color(designHex: "{tokens.success}")
        public static let successSoft = SwiftUI.Color(designHex: "{tokens.success_soft}")
        public static let warning = SwiftUI.Color(designHex: "{tokens.warning}")
        public static let warningSoft = SwiftUI.Color(designHex: "{tokens.warning_soft}")
        public static let info = SwiftUI.Color(designHex: "{tokens.info}")
        public static let infoSoft = SwiftUI.Color(designHex: "{tokens.info_soft}")
    }}

    public enum Typography {{
        public static let family = "{tokens.font_family}"
        public static let heading = Font.custom(family, size: 24).weight(.bold)
        public static let body = Font.custom(family, size: 16).weight(.medium)
        public static let caption = Font.custom(family, size: 14).weight(.medium)
        public static let button = Font.custom(family, size: 14).weight(.bold)
    }}

    public enum Radius {{
        public static let button: CGFloat = 8
        public static let buttonLarge: CGFloat = 12
        public static let input: CGFloat = 12
        public static let badge: CGFloat = 16
        public static let card: CGFloat = 24
    }}

    public enum Stroke {{
        public static let defaultWidth: CGFloat = {border_width}
    }}
}}

public enum DesignButtonVariant: Sendable {{
    case primary
    case secondary
    case dangerPrimary
    case dangerSecondary
}}

public struct DesignButtonStyle: ButtonStyle {{
    private let variant: DesignButtonVariant

    public init(variant: DesignButtonVariant = .primary) {{
        self.variant = variant
    }}

    public func makeBody(configuration: Configuration) -> some View {{
        configuration.label
            .font(DesignTokens.Typography.button)
            .padding(.horizontal, 12)
            .frame(minHeight: 40)
            .background(configuration.isPressed ? pressedBackground : background)
            .foregroundStyle(foreground)
            .overlay(
                RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge)
                    .stroke(DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.defaultWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge))
    }}

    private var background: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButton
        case .secondary: DesignTokens.Color.secondaryButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var pressedBackground: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.brand
        case .secondary: DesignTokens.Color.focusRing
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var foreground: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButtonText
        case .secondary: DesignTokens.Color.secondaryButtonText
        case .dangerPrimary: SwiftUI.Color.white
        case .dangerSecondary: DesignTokens.Color.dangerText
        }}
    }}
}}
"""


def kotlin(tokens: ThemeTokens, package_name: str) -> str:
    border_width = "1.dp" if tokens.uses_borders else "0.dp"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

package {package_name}

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private fun designColor(hex: String): Color {{
    val value = hex.removePrefix("#")
    val rgba = value.toLong(16)
    return if (value.length == 8) {{
        val r = (rgba shr 24) and 0xff
        val g = (rgba shr 16) and 0xff
        val b = (rgba shr 8) and 0xff
        val a = rgba and 0xff
        Color(((a shl 24) or (r shl 16) or (g shl 8) or b).toULong())
    }} else {{
        Color((0xff000000 or rgba).toULong())
    }}
}}

object DesignTheme {{
    const val id = "{tokens.slug}"
    const val name = "{escape_kotlin(tokens.name)}"
    const val description = "{escape_kotlin(tokens.description)}"
}}

object DesignColors {{
    val page = designColor("{tokens.page}")
    val surface = designColor("{tokens.surface}")
    val secondarySurface = designColor("{tokens.secondary_surface}")
    val header = designColor("{tokens.header}")
    val headerBorder = designColor("{tokens.header_border}")
    val footer = designColor("{tokens.footer}")
    val primaryText = designColor("{tokens.primary_text}")
    val secondaryText = designColor("{tokens.secondary_text}")
    val placeholderText = designColor("{tokens.placeholder_text}")
    val border = designColor("{tokens.border}")
    val focusRing = designColor("{tokens.focus_ring}")
    val brand = designColor("{tokens.brand}")
    val primaryButton = designColor("{tokens.primary_button}")
    val primaryButtonText = designColor("{tokens.primary_button_text}")
    val secondaryButton = designColor("{tokens.secondary_button}")
    val secondaryButtonText = designColor("{tokens.secondary_button_text}")
    val danger = designColor("{tokens.danger}")
    val dangerSoft = designColor("{tokens.danger_soft}")
    val dangerText = designColor("{tokens.danger_text}")
    val success = designColor("{tokens.success}")
    val successSoft = designColor("{tokens.success_soft}")
    val warning = designColor("{tokens.warning}")
    val warningSoft = designColor("{tokens.warning_soft}")
    val info = designColor("{tokens.info}")
    val infoSoft = designColor("{tokens.info_soft}")
}}

object DesignTypography {{
    val family = FontFamily.Default
    val headingSize = 24.sp
    val bodySize = 16.sp
    val captionSize = 14.sp
    val buttonWeight = FontWeight.Bold
    const val preferredFamily = "{tokens.font_family}"
}}

enum class DesignButtonVariant {{
    Primary,
    Secondary,
    DangerPrimary,
    DangerSecondary
}}

@Composable
fun DesignButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    variant: DesignButtonVariant = DesignButtonVariant.Primary,
    enabled: Boolean = true,
) {{
    val container = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButton
        DesignButtonVariant.Secondary -> DesignColors.secondaryButton
        DesignButtonVariant.DangerPrimary -> DesignColors.danger
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerSoft
    }}
    val content = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButtonText
        DesignButtonVariant.Secondary -> DesignColors.secondaryButtonText
        DesignButtonVariant.DangerPrimary -> Color.White
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerText
    }}

    Button(
        onClick = onClick,
        modifier = modifier,
        enabled = enabled,
        shape = RoundedCornerShape(12.dp),
        border = BorderStroke({border_width}, DesignColors.border),
        colors = ButtonDefaults.buttonColors(containerColor = container, contentColor = content),
        contentPadding = PaddingValues(horizontal = 12.dp, vertical = 0.dp),
    ) {{
        Text(text = text, fontWeight = DesignTypography.buttonWeight, fontSize = DesignTypography.captionSize)
    }}
}}
"""


def typescript(tokens: ThemeTokens) -> str:
    border_width = "1px" if tokens.uses_borders else "0"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

export const designTheme = {{
  id: "{tokens.slug}",
  name: "{escape_ts(tokens.name)}",
  description: "{escape_ts(tokens.description)}",
}} as const;

export const designTokens = {{
  colors: {{
    page: "{tokens.page}",
    surface: "{tokens.surface}",
    secondarySurface: "{tokens.secondary_surface}",
    header: "{tokens.header}",
    headerBorder: "{tokens.header_border}",
    footer: "{tokens.footer}",
    primaryText: "{tokens.primary_text}",
    secondaryText: "{tokens.secondary_text}",
    placeholderText: "{tokens.placeholder_text}",
    border: "{tokens.border}",
    focusRing: "{tokens.focus_ring}",
    brand: "{tokens.brand}",
    primaryButton: "{tokens.primary_button}",
    primaryButtonText: "{tokens.primary_button_text}",
    secondaryButton: "{tokens.secondary_button}",
    secondaryButtonText: "{tokens.secondary_button_text}",
    danger: "{tokens.danger}",
    dangerSoft: "{tokens.danger_soft}",
    dangerText: "{tokens.danger_text}",
    success: "{tokens.success}",
    successSoft: "{tokens.success_soft}",
    warning: "{tokens.warning}",
    warningSoft: "{tokens.warning_soft}",
    info: "{tokens.info}",
    infoSoft: "{tokens.info_soft}",
  }},
  typography: {{
    fontFamily: "{tokens.font_family}",
    headingWeight: 700,
    bodyWeight: 500,
    lineHeight: 1.2,
  }},
  radii: {{
    button: 8,
    buttonLarge: 12,
    input: 12,
    badge: 16,
    card: 24,
  }},
  borders: {{
    defaultWidth: "{border_width}",
  }},
  motion: {{
    hover: "120ms ease",
    base: "200ms ease",
    modal: "320ms ease",
  }},
}} as const;

export type DesignButtonVariant = "primary" | "secondary" | "dangerPrimary" | "dangerSecondary";
export type DesignBadgeVariant = "info" | "neutral" | "success" | "warning" | "danger";
export type StyleRecipe = Record<string, string | number>;

export const buttonRecipe: Record<DesignButtonVariant, StyleRecipe> = {{
  primary: {{
    background: designTokens.colors.primaryButton,
    color: designTokens.colors.primaryButtonText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  secondary: {{
    background: designTokens.colors.secondaryButton,
    color: designTokens.colors.secondaryButtonText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  dangerPrimary: {{
    background: designTokens.colors.danger,
    color: "#FFFFFF",
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  dangerSecondary: {{
    background: designTokens.colors.dangerSoft,
    color: designTokens.colors.dangerText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
}};

export const componentRecipe = {{
  page: {{
    background: designTokens.colors.page,
    color: designTokens.colors.primaryText,
    fontFamily: designTokens.typography.fontFamily,
  }},
  card: {{
    background: designTokens.colors.surface,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.card,
    padding: 24,
  }},
  input: {{
    background: designTokens.colors.secondarySurface,
    color: designTokens.colors.primaryText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.input,
    minHeight: 40,
  }},
  header: {{
    background: designTokens.colors.header,
    color: designTokens.colors.primaryText,
    borderBottom: `1px solid ${{designTokens.colors.headerBorder}}`,
  }},
  footer: {{
    background: designTokens.colors.footer,
    color: designTokens.colors.secondaryText,
  }},
  badge: {{
    info: {{ background: designTokens.colors.infoSoft, color: designTokens.colors.info }},
    neutral: {{ background: designTokens.colors.secondarySurface, color: designTokens.colors.primaryText }},
    success: {{ background: designTokens.colors.successSoft, color: designTokens.colors.success }},
    warning: {{ background: designTokens.colors.warningSoft, color: designTokens.colors.warning }},
    danger: {{ background: designTokens.colors.dangerSoft, color: designTokens.colors.dangerText }},
  }},
}} as const;
"""


def escape_swift(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def escape_kotlin(value: str) -> str:
    return escape_swift(value)


def escape_ts(value: str) -> str:
    return escape_swift(value)


def write_file(path: Path, content: str, check: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized = content.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != normalized:
            print(f"DIFF {path}")
            for line in difflib.unified_diff(
                current.splitlines(),
                normalized.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ):
                print(line)
            return False
        return True
    path.write_text(normalized)
    return True


def generate(project_root: Path, platform: str, theme_slug: str, package_name: str, check: bool) -> bool:
    tokens = extract_tokens(read_theme(theme_slug))
    project_root = project_root.resolve()

    outputs = {
        "swift": (project_root / "styling.gen.swift", swift(tokens)),
        "kotlin": (project_root / "styling.gen.kt", kotlin(tokens, package_name)),
        "typescript": (project_root / "styling.gen.ts", typescript(tokens)),
    }

    path, content = outputs[platform]
    return write_file(path, content, check)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_root", nargs="?", default=".", help="Project root to receive generated files.")
    parser.add_argument(
        "--platform",
        required=True,
        choices=("swift", "kotlin", "typescript"),
        help="Platform styling file to generate.",
    )
    parser.add_argument(
        "--theme",
        default="light",
        help="Theme directory under themes/ to use. Defaults to light.",
    )
    parser.add_argument(
        "--kotlin-package",
        default="com.designarchitect.designsystem",
        help="Package name for styling.gen.kt.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Print diffs and fail if generated files are stale.",
    )
    args = parser.parse_args()

    try:
        ok = generate(Path(args.project_root), args.platform, args.theme, args.kotlin_package, args.check)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check and not ok:
        return 1

    verb = "Checked" if args.check else "Generated"
    print(f"{verb} {args.platform} design system for theme '{args.theme}' in {Path(args.project_root).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
