#!/usr/bin/env python3
"""Generate design-system components from a selected theme."""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_HEADER = "Generated by design-architect. Do not edit manually."
SCRIPT_DIR = Path(__file__).resolve().parent
SKILL_ROOT = SCRIPT_DIR.parent
THEMES_ROOT = SKILL_ROOT / "themes"


HEX_COLOR_FIELDS = [
    "page",
    "surface",
    "secondarySurface",
    "header",
    "headerBorder",
    "footer",
    "primaryText",
    "secondaryText",
    "placeholderText",
    "border",
    "focusRing",
    "brand",
    "primaryButton",
    "primaryButtonText",
    "secondaryButton",
    "secondaryButtonText",
    "danger",
    "dangerSoft",
    "dangerText",
    "success",
    "successSoft",
    "warning",
    "warningSoft",
    "info",
    "infoSoft",
]


@dataclass(frozen=True)
class ThemeTokens:
    slug: str
    name: str
    description: str
    font_family: str
    page: str
    surface: str
    secondary_surface: str
    header: str
    header_border: str
    footer: str
    primary_text: str
    secondary_text: str
    placeholder_text: str
    border: str
    focus_ring: str
    brand: str
    primary_button: str
    primary_button_text: str
    secondary_button: str
    secondary_button_text: str
    danger: str
    danger_soft: str
    danger_text: str
    success: str
    success_soft: str
    warning: str
    warning_soft: str
    info: str
    info_soft: str
    uses_borders: bool


def available_themes() -> list[str]:
    if not THEMES_ROOT.exists():
        return []
    return sorted(path.name for path in THEMES_ROOT.iterdir() if (path / "theme.json").is_file())


def read_theme(slug: str) -> ThemeTokens:
    theme_dir = THEMES_ROOT / slug
    if not theme_dir.is_dir():
        choices = ", ".join(available_themes()) or "none"
        raise ValueError(f"Unknown theme '{slug}'. Available themes: {choices}.")

    theme_path = theme_dir / "theme.json"
    if not theme_path.is_file():
        raise ValueError(f"Theme '{slug}' is missing theme.json.")

    try:
        data = json.loads(theme_path.read_text())
    except json.JSONDecodeError as error:
        raise ValueError(f"{theme_path} is not valid JSON: {error}") from error

    validate_theme_json(data, theme_path, expected_slug=slug)
    colors = data["colors"]
    typography = data["typography"]
    components = data["components"]

    return ThemeTokens(
        slug=data["id"],
        name=data["name"],
        description=data["description"],
        font_family=typography["fontFamily"],
        page=colors["page"],
        surface=colors["surface"],
        secondary_surface=colors["secondarySurface"],
        header=colors["header"],
        header_border=colors["headerBorder"],
        footer=colors["footer"],
        primary_text=colors["primaryText"],
        secondary_text=colors["secondaryText"],
        placeholder_text=colors["placeholderText"],
        border=colors["border"],
        focus_ring=colors["focusRing"],
        brand=colors["brand"],
        primary_button=colors["primaryButton"],
        primary_button_text=colors["primaryButtonText"],
        secondary_button=colors["secondaryButton"],
        secondary_button_text=colors["secondaryButtonText"],
        danger=colors["danger"],
        danger_soft=colors["dangerSoft"],
        danger_text=colors["dangerText"],
        success=colors["success"],
        success_soft=colors["successSoft"],
        warning=colors["warning"],
        warning_soft=colors["warningSoft"],
        info=colors["info"],
        info_soft=colors["infoSoft"],
        uses_borders=components["usesBorders"],
    )


def validate_theme_json(data: object, path: Path, expected_slug: str | None = None) -> None:
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object.")

    required_top = ("id", "name", "description", "typography", "colors", "components")
    require_keys(data, required_top, path)

    if expected_slug is not None and data["id"] != expected_slug:
        raise ValueError(f"{path} id must match its directory name '{expected_slug}'.")

    for key in ("id", "name", "description"):
        if not isinstance(data[key], str) or not data[key].strip():
            raise ValueError(f"{path} field '{key}' must be a non-empty string.")

    typography = require_object(data, "typography", path)
    require_keys(typography, ("fontFamily", "headingWeight", "bodyWeight", "lineHeight"), path / "typography")
    if not isinstance(typography["fontFamily"], str) or not typography["fontFamily"].strip():
        raise ValueError(f"{path} typography.fontFamily must be a non-empty string.")
    for key in ("headingWeight", "bodyWeight"):
        if not isinstance(typography[key], int):
            raise ValueError(f"{path} typography.{key} must be an integer.")
    if not isinstance(typography["lineHeight"], (int, float)):
        raise ValueError(f"{path} typography.lineHeight must be a number.")

    colors = require_object(data, "colors", path)
    require_keys(colors, HEX_COLOR_FIELDS, path / "colors")
    for key in HEX_COLOR_FIELDS:
        if not is_hex_color(colors[key]):
            raise ValueError(f"{path} colors.{key} must be a #RRGGBB or #RRGGBBAA color.")

    components = require_object(data, "components", path)
    require_keys(components, ("usesBorders",), path / "components")
    if not isinstance(components["usesBorders"], bool):
        raise ValueError(f"{path} components.usesBorders must be a boolean.")


def require_object(data: dict[str, object], key: str, path: Path) -> dict[str, object]:
    value = data[key]
    if not isinstance(value, dict):
        raise ValueError(f"{path} field '{key}' must be an object.")
    return value


def require_keys(data: dict[str, object], keys: tuple[str, ...] | list[str], path: Path) -> None:
    missing = [key for key in keys if key not in data]
    if missing:
        raise ValueError(f"{path} is missing required fields: {', '.join(missing)}.")


def is_hex_color(value: object) -> bool:
    if not isinstance(value, str):
        return False
    raw = value.removeprefix("#")
    return value.startswith("#") and len(raw) in (6, 8) and all(char in "0123456789abcdefABCDEF" for char in raw)


def swift(tokens: ThemeTokens) -> str:
    border_width = "1" if tokens.uses_borders else "0"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})
// swiftlint:disable all

import SwiftUI

private extension Color {{
    init(designHex hex: String) {{
        let value = hex.trimmingCharacters(in: CharacterSet(charactersIn: "#"))
        let scanner = Scanner(string: value)
        var rgba: UInt64 = 0
        scanner.scanHexInt64(&rgba)

        let red: Double
        let green: Double
        let blue: Double
        let alpha: Double

        if value.count == 8 {{
            red = Double((rgba >> 24) & 0xff) / 255
            green = Double((rgba >> 16) & 0xff) / 255
            blue = Double((rgba >> 8) & 0xff) / 255
            alpha = Double(rgba & 0xff) / 255
        }} else {{
            red = Double((rgba >> 16) & 0xff) / 255
            green = Double((rgba >> 8) & 0xff) / 255
            blue = Double(rgba & 0xff) / 255
            alpha = 1
        }}

        self.init(.sRGB, red: red, green: green, blue: blue, opacity: alpha)
    }}
}}

public enum DesignTheme {{
    public static let id = "{tokens.slug}"
    public static let name = "{escape_swift(tokens.name)}"
    public static let description = "{escape_swift(tokens.description)}"
}}

public enum DesignTokens {{
    public enum Color {{
        public static let page = SwiftUI.Color(designHex: "{tokens.page}")
        public static let surface = SwiftUI.Color(designHex: "{tokens.surface}")
        public static let secondarySurface = SwiftUI.Color(designHex: "{tokens.secondary_surface}")
        public static let header = SwiftUI.Color(designHex: "{tokens.header}")
        public static let headerBorder = SwiftUI.Color(designHex: "{tokens.header_border}")
        public static let footer = SwiftUI.Color(designHex: "{tokens.footer}")
        public static let primaryText = SwiftUI.Color(designHex: "{tokens.primary_text}")
        public static let secondaryText = SwiftUI.Color(designHex: "{tokens.secondary_text}")
        public static let placeholderText = SwiftUI.Color(designHex: "{tokens.placeholder_text}")
        public static let border = SwiftUI.Color(designHex: "{tokens.border}")
        public static let focusRing = SwiftUI.Color(designHex: "{tokens.focus_ring}")
        public static let brand = SwiftUI.Color(designHex: "{tokens.brand}")
        public static let primaryButton = SwiftUI.Color(designHex: "{tokens.primary_button}")
        public static let primaryButtonText = SwiftUI.Color(designHex: "{tokens.primary_button_text}")
        public static let secondaryButton = SwiftUI.Color(designHex: "{tokens.secondary_button}")
        public static let secondaryButtonText = SwiftUI.Color(designHex: "{tokens.secondary_button_text}")
        public static let danger = SwiftUI.Color(designHex: "{tokens.danger}")
        public static let dangerSoft = SwiftUI.Color(designHex: "{tokens.danger_soft}")
        public static let dangerText = SwiftUI.Color(designHex: "{tokens.danger_text}")
        public static let success = SwiftUI.Color(designHex: "{tokens.success}")
        public static let successSoft = SwiftUI.Color(designHex: "{tokens.success_soft}")
        public static let warning = SwiftUI.Color(designHex: "{tokens.warning}")
        public static let warningSoft = SwiftUI.Color(designHex: "{tokens.warning_soft}")
        public static let info = SwiftUI.Color(designHex: "{tokens.info}")
        public static let infoSoft = SwiftUI.Color(designHex: "{tokens.info_soft}")
    }}

    public enum Typography {{
        public static let family = "{tokens.font_family}"
        public static let heading = Font.custom(family, size: 24).weight(.bold)
        public static let body = Font.custom(family, size: 16).weight(.medium)
        public static let caption = Font.custom(family, size: 14).weight(.medium)
        public static let button = Font.custom(family, size: 14).weight(.bold)
    }}

    public enum Radius {{
        public static let button: CGFloat = 8
        public static let buttonLarge: CGFloat = 12
        public static let input: CGFloat = 12
        public static let badge: CGFloat = 16
        public static let card: CGFloat = 24
    }}

    public enum Stroke {{
        public static let defaultWidth: CGFloat = {border_width}
    }}
}}

public enum DesignButtonVariant: Sendable {{
    case primary
    case secondary
    case dangerPrimary
    case dangerSecondary
}}

public struct DesignButtonStyle: ButtonStyle {{
    private let variant: DesignButtonVariant

    public init(variant: DesignButtonVariant = .primary) {{
        self.variant = variant
    }}

    public func makeBody(configuration: Configuration) -> some View {{
        configuration.label
            .font(DesignTokens.Typography.button)
            .padding(.horizontal, 12)
            .frame(minHeight: 40)
            .background(configuration.isPressed ? pressedBackground : background)
            .foregroundStyle(foreground)
            .overlay(
                RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge)
                    .stroke(DesignTokens.Color.border, lineWidth: DesignTokens.Stroke.defaultWidth)
            )
            .clipShape(RoundedRectangle(cornerRadius: DesignTokens.Radius.buttonLarge))
    }}

    private var background: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButton
        case .secondary: DesignTokens.Color.secondaryButton
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var pressedBackground: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.brand
        case .secondary: DesignTokens.Color.focusRing
        case .dangerPrimary: DesignTokens.Color.danger
        case .dangerSecondary: DesignTokens.Color.dangerSoft
        }}
    }}

    private var foreground: SwiftUI.Color {{
        switch variant {{
        case .primary: DesignTokens.Color.primaryButtonText
        case .secondary: DesignTokens.Color.secondaryButtonText
        case .dangerPrimary: SwiftUI.Color.white
        case .dangerSecondary: DesignTokens.Color.dangerText
        }}
    }}
}}
"""


def kotlin(tokens: ThemeTokens, package_name: str) -> str:
    border_width = "1.dp" if tokens.uses_borders else "0.dp"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

package {package_name}

import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

private fun designColor(hex: String): Color {{
    val value = hex.removePrefix("#")
    val rgba = value.toLong(16)
    return if (value.length == 8) {{
        val r = (rgba shr 24) and 0xff
        val g = (rgba shr 16) and 0xff
        val b = (rgba shr 8) and 0xff
        val a = rgba and 0xff
        Color(((a shl 24) or (r shl 16) or (g shl 8) or b).toULong())
    }} else {{
        Color((0xff000000 or rgba).toULong())
    }}
}}

object DesignTheme {{
    const val id = "{tokens.slug}"
    const val name = "{escape_kotlin(tokens.name)}"
    const val description = "{escape_kotlin(tokens.description)}"
}}

object DesignColors {{
    val page = designColor("{tokens.page}")
    val surface = designColor("{tokens.surface}")
    val secondarySurface = designColor("{tokens.secondary_surface}")
    val header = designColor("{tokens.header}")
    val headerBorder = designColor("{tokens.header_border}")
    val footer = designColor("{tokens.footer}")
    val primaryText = designColor("{tokens.primary_text}")
    val secondaryText = designColor("{tokens.secondary_text}")
    val placeholderText = designColor("{tokens.placeholder_text}")
    val border = designColor("{tokens.border}")
    val focusRing = designColor("{tokens.focus_ring}")
    val brand = designColor("{tokens.brand}")
    val primaryButton = designColor("{tokens.primary_button}")
    val primaryButtonText = designColor("{tokens.primary_button_text}")
    val secondaryButton = designColor("{tokens.secondary_button}")
    val secondaryButtonText = designColor("{tokens.secondary_button_text}")
    val danger = designColor("{tokens.danger}")
    val dangerSoft = designColor("{tokens.danger_soft}")
    val dangerText = designColor("{tokens.danger_text}")
    val success = designColor("{tokens.success}")
    val successSoft = designColor("{tokens.success_soft}")
    val warning = designColor("{tokens.warning}")
    val warningSoft = designColor("{tokens.warning_soft}")
    val info = designColor("{tokens.info}")
    val infoSoft = designColor("{tokens.info_soft}")
}}

object DesignTypography {{
    val family = FontFamily.Default
    val headingSize = 24.sp
    val bodySize = 16.sp
    val captionSize = 14.sp
    val buttonWeight = FontWeight.Bold
    const val preferredFamily = "{tokens.font_family}"
}}

enum class DesignButtonVariant {{
    Primary,
    Secondary,
    DangerPrimary,
    DangerSecondary
}}

@Composable
fun DesignButton(
    text: String,
    onClick: () -> Unit,
    modifier: Modifier = Modifier,
    variant: DesignButtonVariant = DesignButtonVariant.Primary,
    enabled: Boolean = true,
) {{
    val container = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButton
        DesignButtonVariant.Secondary -> DesignColors.secondaryButton
        DesignButtonVariant.DangerPrimary -> DesignColors.danger
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerSoft
    }}
    val content = when (variant) {{
        DesignButtonVariant.Primary -> DesignColors.primaryButtonText
        DesignButtonVariant.Secondary -> DesignColors.secondaryButtonText
        DesignButtonVariant.DangerPrimary -> Color.White
        DesignButtonVariant.DangerSecondary -> DesignColors.dangerText
    }}

    Button(
        onClick = onClick,
        modifier = modifier,
        enabled = enabled,
        shape = RoundedCornerShape(12.dp),
        border = BorderStroke({border_width}, DesignColors.border),
        colors = ButtonDefaults.buttonColors(containerColor = container, contentColor = content),
        contentPadding = PaddingValues(horizontal = 12.dp, vertical = 0.dp),
    ) {{
        Text(text = text, fontWeight = DesignTypography.buttonWeight, fontSize = DesignTypography.captionSize)
    }}
}}
"""


def typescript(tokens: ThemeTokens) -> str:
    border_width = "1px" if tokens.uses_borders else "0"
    return f"""// {GENERATED_HEADER}
// Theme: {tokens.name} ({tokens.slug})

export const designTheme = {{
  id: "{tokens.slug}",
  name: "{escape_ts(tokens.name)}",
  description: "{escape_ts(tokens.description)}",
}} as const;

export const designTokens = {{
  colors: {{
    page: "{tokens.page}",
    surface: "{tokens.surface}",
    secondarySurface: "{tokens.secondary_surface}",
    header: "{tokens.header}",
    headerBorder: "{tokens.header_border}",
    footer: "{tokens.footer}",
    primaryText: "{tokens.primary_text}",
    secondaryText: "{tokens.secondary_text}",
    placeholderText: "{tokens.placeholder_text}",
    border: "{tokens.border}",
    focusRing: "{tokens.focus_ring}",
    brand: "{tokens.brand}",
    primaryButton: "{tokens.primary_button}",
    primaryButtonText: "{tokens.primary_button_text}",
    secondaryButton: "{tokens.secondary_button}",
    secondaryButtonText: "{tokens.secondary_button_text}",
    danger: "{tokens.danger}",
    dangerSoft: "{tokens.danger_soft}",
    dangerText: "{tokens.danger_text}",
    success: "{tokens.success}",
    successSoft: "{tokens.success_soft}",
    warning: "{tokens.warning}",
    warningSoft: "{tokens.warning_soft}",
    info: "{tokens.info}",
    infoSoft: "{tokens.info_soft}",
  }},
  typography: {{
    fontFamily: "{tokens.font_family}",
    headingWeight: 700,
    bodyWeight: 500,
    lineHeight: 1.2,
  }},
  radii: {{
    button: 8,
    buttonLarge: 12,
    input: 12,
    badge: 16,
    card: 24,
  }},
  borders: {{
    defaultWidth: "{border_width}",
  }},
  motion: {{
    hover: "120ms ease",
    base: "200ms ease",
    modal: "320ms ease",
  }},
}} as const;

export type DesignButtonVariant = "primary" | "secondary" | "dangerPrimary" | "dangerSecondary";
export type DesignBadgeVariant = "info" | "neutral" | "success" | "warning" | "danger";
export type StyleRecipe = Record<string, string | number>;

export const buttonRecipe: Record<DesignButtonVariant, StyleRecipe> = {{
  primary: {{
    background: designTokens.colors.primaryButton,
    color: designTokens.colors.primaryButtonText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  secondary: {{
    background: designTokens.colors.secondaryButton,
    color: designTokens.colors.secondaryButtonText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  dangerPrimary: {{
    background: designTokens.colors.danger,
    color: "#FFFFFF",
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
  dangerSecondary: {{
    background: designTokens.colors.dangerSoft,
    color: designTokens.colors.dangerText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
  }},
}};

export const componentRecipe = {{
  page: {{
    background: designTokens.colors.page,
    color: designTokens.colors.primaryText,
    fontFamily: designTokens.typography.fontFamily,
  }},
  card: {{
    background: designTokens.colors.surface,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.card,
    padding: 24,
  }},
  input: {{
    background: designTokens.colors.secondarySurface,
    color: designTokens.colors.primaryText,
    border: `${{designTokens.borders.defaultWidth}} solid ${{designTokens.colors.border}}`,
    borderRadius: designTokens.radii.input,
    minHeight: 40,
  }},
  header: {{
    background: designTokens.colors.header,
    color: designTokens.colors.primaryText,
    borderBottom: `1px solid ${{designTokens.colors.headerBorder}}`,
  }},
  footer: {{
    background: designTokens.colors.footer,
    color: designTokens.colors.secondaryText,
  }},
  badge: {{
    info: {{ background: designTokens.colors.infoSoft, color: designTokens.colors.info }},
    neutral: {{ background: designTokens.colors.secondarySurface, color: designTokens.colors.primaryText }},
    success: {{ background: designTokens.colors.successSoft, color: designTokens.colors.success }},
    warning: {{ background: designTokens.colors.warningSoft, color: designTokens.colors.warning }},
    danger: {{ background: designTokens.colors.dangerSoft, color: designTokens.colors.dangerText }},
  }},
}} as const;
"""


def escape_swift(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def escape_kotlin(value: str) -> str:
    return escape_swift(value)


def escape_ts(value: str) -> str:
    return escape_swift(value)


def write_file(path: Path, content: str, check: bool) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    normalized = content.rstrip() + "\n"
    if check:
        current = path.read_text() if path.exists() else ""
        if current != normalized:
            print(f"DIFF {path}")
            for line in difflib.unified_diff(
                current.splitlines(),
                normalized.splitlines(),
                fromfile=str(path),
                tofile=f"{path} (generated)",
                lineterm="",
            ):
                print(line)
            return False
        return True
    path.write_text(normalized)
    return True


def generate(project_root: Path, platform: str, theme_slug: str, package_name: str, check: bool) -> bool:
    tokens = read_theme(theme_slug)
    project_root = project_root.resolve()

    outputs = {
        "swift": (project_root / "styling.gen.swift", swift(tokens)),
        "kotlin": (project_root / "styling.gen.kt", kotlin(tokens, package_name)),
        "typescript": (project_root / "styling.gen.ts", typescript(tokens)),
    }

    path, content = outputs[platform]
    return write_file(path, content, check)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("project_root", nargs="?", default=".", help="Project root to receive generated files.")
    parser.add_argument(
        "--platform",
        required=True,
        choices=("swift", "kotlin", "typescript"),
        help="Platform styling file to generate.",
    )
    parser.add_argument(
        "--theme",
        default="light",
        help="Theme directory under themes/ to use. Defaults to light.",
    )
    parser.add_argument(
        "--kotlin-package",
        default="com.designarchitect.designsystem",
        help="Package name for styling.gen.kt.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Print diffs and fail if generated files are stale.",
    )
    args = parser.parse_args()

    try:
        ok = generate(Path(args.project_root), args.platform, args.theme, args.kotlin_package, args.check)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    if args.check and not ok:
        return 1

    verb = "Checked" if args.check else "Generated"
    print(f"{verb} {args.platform} design system for theme '{args.theme}' in {Path(args.project_root).resolve()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
